import { z } from "zod";
import {
	fontEnum,
	hexColor,
	pageSchema,
	type ThemePresetMap,
	watermarkSchema,
} from "./common";

export const diplomaThemeSchema = z.object({
	page: pageSchema,
	watermark: watermarkSchema,

	fonts: z.object({
		main: fontEnum,
		title: fontEnum,
		subtitle: fontEnum,
		header: fontEnum,
		legalText: fontEnum,
		studentName: fontEnum,
		studentInfo: fontEnum,
		footer: fontEnum,
		signature: fontEnum,
		mention: fontEnum,
		reference: fontEnum,
	}),

	sizes: z.object({
		title: z.number().min(16).max(36),
		subtitle: z.number().min(12).max(28),
		header: z.number().min(7).max(14),
		content: z.number().min(8).max(16),
		legalText: z.number().min(6).max(12),
		footer: z.number().min(7).max(12),
		studentName: z.number().min(10).max(22),
		studentInfo: z.number().min(8).max(14),
		mention: z.number().min(8).max(18),
		matricule: z.number().min(8).max(18),
		referenceNumber: z.number().min(7).max(14),
	}),

	colors: z.object({
		primary: hexColor,
		secondary: hexColor,
		accent: hexColor,
		fullName: hexColor,
		mention: hexColor,
		matricule: hexColor,
		diplomaTitle: hexColor,
		yearObtention: hexColor,
		juryDates: hexColor,
		outerBorder: hexColor,
		innerBorder: hexColor,
	}),

	borders: z.object({
		outerWidth: z.number().min(0).max(15),
		innerWidth: z.number().min(0).max(5),
	}),

	logos: z.object({
		facultyLogoSize: z.number().min(30).max(120),
		universityLogoSize: z.number().min(60).max(150),
		ministryLogoSize: z.number().min(40).max(120),
		coatOfArmsSize: z.number().min(60).max(150),
		facultyLogoOffsetX: z.number().min(-80).max(120),
		facultyLogoOffsetY: z.number().min(-40).max(40),
		coatOfArmsOffsetX: z.number().min(-80).max(80),
		coatOfArmsOffsetY: z.number().min(-40).max(40),
		ministryLogoOffsetX: z.number().min(-120).max(80),
		ministryLogoOffsetY: z.number().min(-40).max(40),
	}),

	qrCode: z.object({
		enabled: z.boolean(),
		compactPayload: z.boolean(),
		size: z.number().min(40).max(120),
		offsetX: z.number().min(-100).max(100),
		offsetY: z.number().min(-50).max(50),
	}),

	titleEffects: z.object({
		lineHeight: z.number().min(0.8).max(2),
		letterSpacing: z.number().min(-2).max(10),
		shadow: z.boolean(),
		shadowColor: hexColor,
		shadowOffsetX: z.number().min(0).max(10),
		shadowOffsetY: z.number().min(0).max(10),
		shadowBlur: z.number().min(0).max(20),
	}),

	spacing: z.object({
		headerLineHeight: z.number().min(1).max(2),
		titleBlockMarginTop: z.number().min(0).max(20),
		titleBlockMarginBottom: z.number().min(0).max(20),
		ministerBlockMarginBottom: z.number().min(0).max(15),
		recipientBlockMarginBottom: z.number().min(0).max(15),
		signatureBlockMarginTop: z.number().min(0).max(15),
		sectionSpacing: z.number().min(2).max(12),
	}),

	display: z.object({
		bilingual: z.boolean(),
		primaryLanguage: z.enum(["french", "english"]),
	}),
});

export type DiplomaTheme = z.infer<typeof diplomaThemeSchema>;

export const diplomaClassicTheme: DiplomaTheme = {
	page: {
		size: "A4",
		orientation: "landscape",
		margins: { top: 6, right: 6, bottom: 6, left: 6 },
	},
	watermark: {
		enabled: true,
		text: "ORIGINAL",
		color: "#000080",
		textOpacity: 0.05,
		logoOpacity: 0.1,
		logoSize: 400,
		textSize: 20,
	},
	fonts: {
		main: "Times New Roman, serif",
		title: "Georgia, serif",
		subtitle: "Times New Roman, serif",
		header: "Times New Roman, serif",
		legalText: "Times New Roman, serif",
		studentName: "Times New Roman, serif",
		studentInfo: "Times New Roman, serif",
		footer: "Times New Roman, serif",
		signature: "Times New Roman, serif",
		mention: "Times New Roman, serif",
		reference: "Times New Roman, serif",
	},
	sizes: {
		title: 20,
		subtitle: 16,
		header: 9,
		content: 10,
		legalText: 7.5,
		footer: 8.5,
		studentName: 13,
		studentInfo: 9.5,
		mention: 11.5,
		matricule: 11.5,
		referenceNumber: 9,
	},
	colors: {
		primary: "#000080",
		secondary: "#000000",
		accent: "#000080",
		fullName: "#000080",
		mention: "#000080",
		matricule: "#000080",
		diplomaTitle: "#000080",
		yearObtention: "#000080",
		juryDates: "#000000",
		outerBorder: "#000080",
		innerBorder: "#000080",
	},
	borders: { outerWidth: 8, innerWidth: 1 },
	logos: {
		facultyLogoSize: 55,
		universityLogoSize: 100,
		ministryLogoSize: 70,
		coatOfArmsSize: 100,
		facultyLogoOffsetX: 50,
		facultyLogoOffsetY: 0,
		coatOfArmsOffsetX: 0,
		coatOfArmsOffsetY: 0,
		ministryLogoOffsetX: -50,
		ministryLogoOffsetY: 0,
	},
	qrCode: {
		enabled: true,
		compactPayload: false,
		size: 50,
		offsetX: 0,
		offsetY: 0,
	},
	titleEffects: {
		lineHeight: 1.1,
		letterSpacing: 0,
		shadow: true,
		shadowColor: "#000080",
		shadowOffsetX: 3,
		shadowOffsetY: 3,
		shadowBlur: 6,
	},
	spacing: {
		headerLineHeight: 1.15,
		titleBlockMarginTop: 0,
		titleBlockMarginBottom: 5,
		ministerBlockMarginBottom: 3,
		recipientBlockMarginBottom: 0,
		signatureBlockMarginTop: 4,
		sectionSpacing: 5,
	},
	display: { bilingual: true, primaryLanguage: "french" },
};

export const diplomaThemePresets: ThemePresetMap<DiplomaTheme> = {
	classic: diplomaClassicTheme,
	elegant: {
		...diplomaClassicTheme,
		fonts: Object.fromEntries(
			Object.keys(diplomaClassicTheme.fonts).map((k) => [k, "Garamond, serif"]),
		) as DiplomaTheme["fonts"],
		sizes: { ...diplomaClassicTheme.sizes, title: 22, subtitle: 18 },
		colors: {
			...diplomaClassicTheme.colors,
			primary: "#1a1a4d",
			accent: "#1a1a4d",
			fullName: "#1a1a4d",
			mention: "#1a1a4d",
			matricule: "#1a1a4d",
			diplomaTitle: "#1a1a4d",
			yearObtention: "#1a1a4d",
			outerBorder: "#1a1a4d",
			innerBorder: "#1a1a4d",
		},
		borders: { outerWidth: 10, innerWidth: 1 },
		watermark: {
			...diplomaClassicTheme.watermark,
			color: "#1a1a4d",
		},
		titleEffects: {
			...diplomaClassicTheme.titleEffects,
			letterSpacing: 2,
			shadowColor: "#1a1a4d",
		},
	},
	modern: {
		...diplomaClassicTheme,
		fonts: Object.fromEntries(
			Object.keys(diplomaClassicTheme.fonts).map((k) => [
				k,
				k === "title" ? "Arial, sans-serif" : "Calibri, sans-serif",
			]),
		) as DiplomaTheme["fonts"],
		sizes: { ...diplomaClassicTheme.sizes, title: 24, subtitle: 20 },
		colors: {
			...diplomaClassicTheme.colors,
			primary: "#004d99",
			accent: "#004d99",
			fullName: "#004d99",
			mention: "#004d99",
			matricule: "#004d99",
			diplomaTitle: "#004d99",
			yearObtention: "#004d99",
			outerBorder: "#004d99",
			innerBorder: "#004d99",
		},
		borders: { outerWidth: 6, innerWidth: 2 },
		watermark: { ...diplomaClassicTheme.watermark, color: "#004d99" },
		titleEffects: {
			...diplomaClassicTheme.titleEffects,
			shadow: false,
			shadowColor: "#004d99",
		},
	},
	compact: {
		...diplomaClassicTheme,
		sizes: {
			...diplomaClassicTheme.sizes,
			title: 18,
			subtitle: 14,
			header: 8,
			content: 9,
			legalText: 7,
			footer: 8,
			studentName: 11,
			studentInfo: 9,
			mention: 10,
			matricule: 10,
		},
		spacing: { ...diplomaClassicTheme.spacing, sectionSpacing: 3 },
	},
	large: {
		...diplomaClassicTheme,
		sizes: {
			...diplomaClassicTheme.sizes,
			title: 24,
			subtitle: 20,
			header: 11,
			content: 12,
			legalText: 9,
			footer: 10,
			studentName: 16,
			studentInfo: 12,
			mention: 13,
			matricule: 13,
		},
		spacing: { ...diplomaClassicTheme.spacing, sectionSpacing: 7 },
	},
};
