import z from "zod";

export const upsertInstitutionSchema = z.object({
	code: z.string().min(1),
	type: z.enum(["university", "institution", "faculty"]).default("institution"),
	shortName: z.string().optional(),
	nameFr: z.string().min(1),
	nameEn: z.string().min(1),
	legalNameFr: z.string().optional(),
	legalNameEn: z.string().optional(),
	sloganFr: z.string().optional(),
	sloganEn: z.string().optional(),
	descriptionFr: z.string().optional(),
	descriptionEn: z.string().optional(),
	addressFr: z.string().optional(),
	addressEn: z.string().optional(),
	contactEmail: z.string().email().optional(),
	contactPhone: z.string().optional(),
	fax: z.string().optional(),
	postalBox: z.string().optional(),
	website: z.string().url().optional(),
	logoUrl: z.string().url().optional(),
	coverImageUrl: z.string().url().optional(),
	organizationId: z.string().optional(),
	parentInstitutionId: z.string().optional(),
	institutionId: z.string().optional(),
	defaultAcademicYearId: z.string().optional(),
	registrationFormatId: z.string().optional(),
	timezone: z.string().optional(),
	metadata: z.record(z.unknown()).optional(),
});
