/**
 * TKAMS Secondaire — Local Dev Seed
 *
 * Creates one institution with a complete academic year, class roster,
 * subjects, terms, and a few sample assessments so the UI is usable
 * immediately after running `bun run seed`.
 *
 * Usage:
 *   bun run seed             # create everything
 *   bun run seed --reset     # wipe PGlite data dir then re-seed (USE_PGLITE only)
 */

import { randomUUID } from "node:crypto";
import { hashPassword } from "better-auth/crypto";
import { eq } from "drizzle-orm";
import { account, member, organization, user } from "./src/db/auth";
import { db, pushSchema } from "./src/db/index";
import {
	academicYears,
	assessments,
	classes,
	enrollments,
	institutions,
	staff,
	students,
	subjectAssignments,
	subjects,
	terms,
	tracks,
} from "./src/db/schema";

const ADMIN_EMAIL = process.env.SYSTEM_ADMIN_EMAIL ?? "admin@tkams.io";
const ADMIN_PASSWORD = process.env.SYSTEM_ADMIN_PASSWORD ?? "Admin1234!";
const SCHOOL_NAME = "Lycée de Démonstration";
const SCHOOL_CITY = "Yaoundé";
const ACADEMIC_YEAR = "2025-2026";

async function log(msg: string) {
	console.log(`  ▸ ${msg}`);
}

// ─── 1. Auth user (admin) ─────────────────────────────────────────────────────

async function ensureAdminUser(): Promise<string> {
	// Check if user already exists
	const existing = await db
		.select({ id: user.id })
		.from(user)
		.where(eq(user.email, ADMIN_EMAIL))
		.limit(1);

	if (existing[0]) {
		await log(
			`Auth user already exists: ${ADMIN_EMAIL} (id=${existing[0].id})`,
		);
		return existing[0].id;
	}

	const userId = randomUUID();
	// Use Better-Auth's own hashPassword so the format matches exactly.
	const hashedPassword = await hashPassword(ADMIN_PASSWORD);

	await db.insert(user).values({
		id: userId,
		name: "Administrateur Système",
		email: ADMIN_EMAIL,
		emailVerified: true,
		createdAt: new Date(),
		updatedAt: new Date(),
	});

	// Insert the credential account (providerId = "credential" for email/password)
	await db.insert(account).values({
		id: randomUUID(),
		userId,
		accountId: ADMIN_EMAIL,
		providerId: "credential",
		issuer: "credential",
		password: hashedPassword,
		createdAt: new Date(),
		updatedAt: new Date(),
	});

	await log(`Created auth user: ${ADMIN_EMAIL} (id=${userId})`);
	return userId;
}

// ─── 2. Institution + Better-Auth org ────────────────────────────────────────

async function ensureInstitution(
	adminUserId: string,
): Promise<{ institutionId: string; staffId: string }> {
	// Check if institution already exists for this slug
	const slug = "lycee-demo";
	const existingOrg = await db
		.select({ id: organization.id })
		.from(organization)
		.where(eq(organization.slug, slug))
		.limit(1);
	if (existingOrg[0]?.id) {
		const institutionId = existingOrg[0].id;
		// Find the admin staff record
		const existingStaff = await db
			.select()
			.from(staff)
			.where(eq(staff.authUserId, adminUserId))
			.limit(1);
		const staffId = existingStaff[0]?.id ?? adminUserId;
		await log(`Institution already exists (id=${institutionId})`);
		return { institutionId, staffId };
	}

	const orgId = randomUUID();

	// Better-Auth organization row
	await db
		.insert(organization)
		.values({
			id: orgId,
			name: SCHOOL_NAME,
			slug,
			createdAt: new Date(),
		})
		.onConflictDoNothing();

	// Application institution
	await db
		.insert(institutions)
		.values({
			id: orgId,
			name: SCHOOL_NAME,
			city: SCHOOL_CITY,
			type: "lycee",
			assessmentMode: "six_sequence",
		})
		.onConflictDoNothing();

	// Staff record for admin (id auto-generated by id() helper)
	const [adminStaff] = await db
		.insert(staff)
		.values({
			institutionId: orgId,
			authUserId: adminUserId,
			firstName: "Administrateur",
			lastName: "Système",
			email: ADMIN_EMAIL,
			role: "admin",
		})
		.returning();

	// Better-Auth member (admin role)
	await db
		.insert(member)
		.values({
			id: randomUUID(),
			organizationId: orgId,
			userId: adminUserId,
			role: "admin",
			createdAt: new Date(),
		})
		.onConflictDoNothing();

	await log(
		`Created institution: ${SCHOOL_NAME} (id=${orgId}, staffId=${adminStaff?.id})`,
	);
	return { institutionId: orgId, staffId: adminStaff?.id };
}

// ─── 3. Academic year ─────────────────────────────────────────────────────────

async function ensureAcademicYear(institutionId: string): Promise<string> {
	const existing = await db
		.select()
		.from(academicYears)
		.where(eq(academicYears.institutionId, institutionId))
		.limit(1);
	if (existing[0]) {
		await log(`Academic year already exists: ${existing[0].name}`);
		return existing[0].id;
	}

	const [year] = await db
		.insert(academicYears)
		.values({
			institutionId,
			name: ACADEMIC_YEAR,
			startDate: new Date("2025-09-01"),
			endDate: new Date("2026-07-31"),
			status: "active",
			assessmentMode: "six_sequence",
		})
		.returning();

	await log(`Created academic year: ${ACADEMIC_YEAR}`);
	return year?.id;
}

// ─── 4. Terms ─────────────────────────────────────────────────────────────────

async function ensureTerms(
	institutionId: string,
	academicYearId: string,
): Promise<string[]> {
	const existing = await db
		.select()
		.from(terms)
		.where(eq(terms.academicYearId, academicYearId));
	if (existing.length >= 3) {
		await log("Terms already exist");
		return existing.map((t) => t.id);
	}

	const TERMS = [
		{ n: 1, start: "2025-09-01", end: "2025-12-20" },
		{ n: 2, start: "2026-01-05", end: "2026-04-10" },
		{ n: 3, start: "2026-04-20", end: "2026-07-10" },
	];

	const inserted = await db
		.insert(terms)
		.values(
			TERMS.map((t) => ({
				institutionId,
				academicYearId,
				termNumber: t.n,
				startDate: new Date(t.start),
				endDate: new Date(t.end),
				status: t.n === 1 ? "closed" : t.n === 2 ? "open" : "open",
			})),
		)
		.returning();

	await log("Created 3 terms");
	return inserted.map((t) => t.id);
}

// ─── 5. Tracks (filières) ────────────────────────────────────────────────────

async function ensureTracks(institutionId: string): Promise<string[]> {
	const existing = await db
		.select()
		.from(tracks)
		.where(eq(tracks.institutionId, institutionId));
	if (existing.length > 0) {
		await log(`Tracks already exist (${existing.length})`);
		return existing.map((t) => t.id);
	}

	const TRACKS = [
		{ name: "Terminale C", code: "TLE-C", cycleLevel: "second_cycle" },
		{ name: "Terminale D", code: "TLE-D", cycleLevel: "second_cycle" },
		{ name: "Première A", code: "1ERE-A", cycleLevel: "second_cycle" },
		{ name: "Troisième", code: "3EME", cycleLevel: "first_cycle" },
	] as const;

	const inserted = await db
		.insert(tracks)
		.values(TRACKS.map((t) => ({ institutionId, ...t, isOfficial: true })))
		.returning();

	await log(`Created ${inserted.length} tracks`);
	return inserted.map((t) => t.id);
}

// ─── 6. Subjects ─────────────────────────────────────────────────────────────

async function ensureSubjects(
	institutionId: string,
): Promise<Array<{ id: string; name: string }>> {
	const existing = await db
		.select()
		.from(subjects)
		.where(eq(subjects.institutionId, institutionId));
	if (existing.length > 0) {
		await log(`Subjects already exist (${existing.length})`);
		return existing.map((s) => ({ id: s.id, name: s.name }));
	}

	const SUBJECTS = [
		{
			name: "Mathematics",
			nameFr: "Mathématiques",
			code: "MATH",
			group: "sciences",
			coeff: 5,
		},
		{
			name: "Physics & Chemistry",
			nameFr: "Physique-Chimie",
			code: "PC",
			group: "sciences",
			coeff: 4,
		},
		{
			name: "Life & Earth Sciences",
			nameFr: "SVT",
			code: "SVT",
			group: "sciences",
			coeff: 3,
		},
		{
			name: "French",
			nameFr: "Français",
			code: "FR",
			group: "languages",
			coeff: 4,
		},
		{
			name: "English",
			nameFr: "Anglais",
			code: "EN",
			group: "languages",
			coeff: 3,
		},
		{
			name: "History & Geography",
			nameFr: "HG",
			code: "HG",
			group: "humanities",
			coeff: 2,
		},
		{
			name: "Philosophy",
			nameFr: "Philosophie",
			code: "PHILO",
			group: "humanities",
			coeff: 2,
		},
		{
			name: "Physical Education",
			nameFr: "EPS",
			code: "EPS",
			group: "pe",
			coeff: 1,
		},
	];

	const inserted = await db
		.insert(subjects)
		.values(
			SUBJECTS.map((s) => ({
				institutionId,
				name: s.name,
				nameFr: s.nameFr,
				code: s.code,
				subjectGroup: s.group,
			})),
		)
		.returning();

	await log(`Created ${inserted.length} subjects`);
	return inserted.map((s) => ({ id: s.id, name: s.name }));
}

// ─── 7. Class ─────────────────────────────────────────────────────────────────

async function ensureClass(
	institutionId: string,
	academicYearId: string,
	trackId: string,
): Promise<string> {
	const existing = await db
		.select()
		.from(classes)
		.where(eq(classes.academicYearId, academicYearId))
		.limit(1);
	if (existing[0]) {
		await log(`Class already exists: ${existing[0].name}`);
		return existing[0].id;
	}

	const [cls] = await db
		.insert(classes)
		.values({
			institutionId,
			academicYearId,
			trackId,
			name: "Terminale C1",
			code: "TLE-C1",
			level: "Tle",
			maxCapacity: 50,
		})
		.returning();

	await log("Created class: Terminale C1");
	return cls?.id;
}

// ─── 8. Students + Enrollments ───────────────────────────────────────────────

const STUDENT_DATA = [
	{
		firstName: "Aminatou",
		lastName: "BELLO",
		gender: "F",
		mnu: "MNU-2025-001",
	},
	{
		firstName: "Paul-Henri",
		lastName: "NGASSA",
		gender: "M",
		mnu: "MNU-2025-002",
	},
	{
		firstName: "Cécile",
		lastName: "EKWALLA",
		gender: "F",
		mnu: "MNU-2025-003",
	},
	{ firstName: "Boris", lastName: "TAMGHO", gender: "M", mnu: "MNU-2025-004" },
	{ firstName: "Fatima", lastName: "DJOUGA", gender: "F", mnu: "MNU-2025-005" },
	{
		firstName: "Jean-Baptiste",
		lastName: "ONDO",
		gender: "M",
		mnu: "MNU-2025-006",
	},
	{ firstName: "Sandra", lastName: "MVONDO", gender: "F", mnu: "MNU-2025-007" },
	{ firstName: "David", lastName: "NKOLO", gender: "M", mnu: "MNU-2025-008" },
	{
		firstName: "Marie-Claire",
		lastName: "ESSOMBA",
		gender: "F",
		mnu: "MNU-2025-009",
	},
	{
		firstName: "Patrick",
		lastName: "MBARGA",
		gender: "M",
		mnu: "MNU-2025-010",
	},
];

async function ensureStudents(
	institutionId: string,
	academicYearId: string,
	classId: string,
): Promise<string[]> {
	const existing = await db
		.select()
		.from(enrollments)
		.where(eq(enrollments.classId, classId));
	if (existing.length > 0) {
		await log(`Students/enrollments already exist (${existing.length})`);
		return existing.map((e) => e.studentId);
	}

	const insertedStudents = await db
		.insert(students)
		.values(
			STUDENT_DATA.map((s) => ({
				institutionId,
				...s,
				reportCardLanguage: "fr" as const,
			})),
		)
		.returning();

	const _insertedEnrollments = await db
		.insert(enrollments)
		.values(
			insertedStudents.map((s) => ({
				institutionId,
				studentId: s.id,
				academicYearId,
				classId,
				status: "active" as const,
				admissionType: "new" as const,
			})),
		)
		.returning();

	await log(`Created ${insertedStudents.length} students + enrollments`);
	return insertedStudents.map((s) => s.id);
}

// ─── 9. Sample assessments ────────────────────────────────────────────────────

async function ensureAssessments(
	institutionId: string,
	classId: string,
	termId: string,
	studentIds: string[],
	subjectList: Array<{ id: string; name: string }>,
	adminStaffId: string,
) {
	// Check if assessments already seeded
	const existing = await db
		.select()
		.from(assessments)
		.where(eq(assessments.classId, classId))
		.limit(1);
	if (existing[0]) {
		await log("Assessments already seeded");
		return;
	}

	const mathSubject = subjectList.find((s) => s.name === "Mathematics");
	const frSubject = subjectList.find((s) => s.name === "French");
	if (!mathSubject || !frSubject) return;

	const rows = [];
	for (const studentId of studentIds) {
		// Seq 1 + Seq 2 for Math
		const mathSeq1 = 10 + Math.random() * 9;
		const mathSeq2 = 10 + Math.random() * 9;
		rows.push(
			{
				institutionId,
				studentId,
				classId,
				termId,
				subjectId: mathSubject.id,
				assessmentType: "sequence_1" as const,
				value: mathSeq1.toFixed(2),
				enteredById: adminStaffId,
			},
			{
				institutionId,
				studentId,
				classId,
				termId,
				subjectId: mathSubject.id,
				assessmentType: "sequence_2" as const,
				value: mathSeq2.toFixed(2),
				enteredById: adminStaffId,
			},
		);

		// Seq 1 + Seq 2 for French
		const frSeq1 = 8 + Math.random() * 11;
		const frSeq2 = 8 + Math.random() * 11;
		rows.push(
			{
				institutionId,
				studentId,
				classId,
				termId,
				subjectId: frSubject.id,
				assessmentType: "sequence_1" as const,
				value: frSeq1.toFixed(2),
				enteredById: adminStaffId,
			},
			{
				institutionId,
				studentId,
				classId,
				termId,
				subjectId: frSubject.id,
				assessmentType: "sequence_2" as const,
				value: frSeq2.toFixed(2),
				enteredById: adminStaffId,
			},
		);
	}

	await db.insert(assessments).values(rows).onConflictDoNothing();
	await log(
		`Created ${rows.length} sample assessments (Math + French, Seq 1-2)`,
	);
}

// ─── 9. Subject Assignments ───────────────────────────────────────────────────

async function ensureSubjectAssignments(
	institutionId: string,
	academicYearId: string,
	classId: string,
	staffId: string,
	subjectList: Array<{ id: string; name: string }>,
): Promise<void> {
	const existing = await db
		.select({ id: subjectAssignments.id })
		.from(subjectAssignments)
		.where(eq(subjectAssignments.classId, classId))
		.limit(1);
	if (existing.length > 0) {
		await log("Subject assignments already exist");
		return;
	}
	await db.insert(subjectAssignments).values(
		subjectList.map((s) => ({
			institutionId,
			academicYearId,
			classId,
			subjectId: s.id,
			staffId,
		})),
	);
	await log(`Created ${subjectList.length} subject assignments`);
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
	console.log("\n🌱  TKAMS Secondaire — Seed\n");

	// Ensure all tables exist (runs migrations + auth table DDL for PGlite)
	await pushSchema();

	const adminUserId = await ensureAdminUser();
	const { institutionId, staffId } = await ensureInstitution(adminUserId);
	const academicYearId = await ensureAcademicYear(institutionId);
	const termIds = await ensureTerms(institutionId, academicYearId);
	const trackIds = await ensureTracks(institutionId);
	const subjectList = await ensureSubjects(institutionId);
	const classId = await ensureClass(
		institutionId,
		academicYearId,
		trackIds[0]!,
	);
	await ensureSubjectAssignments(
		institutionId,
		academicYearId,
		classId,
		staffId,
		subjectList,
	);

	const studentIds = await ensureStudents(
		institutionId,
		academicYearId,
		classId,
	);

	// Seed assessments for term 1 (index 0)
	await ensureAssessments(
		institutionId,
		classId,
		termIds[0]!,
		studentIds,
		subjectList,
		staffId,
	);

	console.log(`
✅  Seed complete!

  Institution : ${SCHOOL_NAME}
  Admin login : ${ADMIN_EMAIL}
  Password    : ${ADMIN_PASSWORD}

  Org ID (set as active org in the app): ${institutionId}

  To log in:
    1. Start the server:  bun dev:server
    2. Start the client:  bun dev:client
    3. Go to http://localhost:5173 and sign in with the credentials above.
    4. The first sign-in will not have an active org — the app will
       ask you to select one. Pick "${SCHOOL_NAME}".
`);
}

main().catch((err) => {
	console.error("❌  Seed failed:", err);
	process.exit(1);
});
