// Generated by Cypress Author — 2026-09-04

describe("Authentication — Login", () => {
	// TC-AUTH-01: Institution admin logs in → redirected to /, sidebar visible
	describe("TC-AUTH-01: Admin login success", () => {
		beforeEach(() => {
			cy.loginAs("admin");
		});

		it("redirects to / and shows sidebar after admin login", () => {
			cy.visit("/#/");
			cy.url().should("not.include", "/login");
			// shadcn Sidebar uses <div data-sidebar="sidebar">, not <aside> with role=complementary
			cy.get("[data-sidebar='sidebar']").should("exist");
		});
	});

	// TC-AUTH-02: Wrong password → error displayed, remain on /login
	describe("TC-AUTH-02: Wrong password shows error", () => {
		beforeEach(() => {
			cy.visit("/#/login");
		});

		it("shows error message and stays on /login with wrong password", () => {
			cy.intercept("POST", "**/api/auth/sign-in/email**").as("signIn");

			cy.findByLabelText(/adresse email|email/i).type(
				Cypress.env("ADMIN_EMAIL") as string,
			);
			cy.findByLabelText(/mot de passe|password/i).type("WrongPassword999!");
			cy.findByRole("button", { name: /se connecter|sign in/i }).click();

			cy.wait("@signIn");
			cy.url().should("include", "/login");
			cy.findByRole("alert").should("be.visible").and("not.be.empty");
		});
	});

	// TC-AUTH-03: 2FA stub — intercept sign-in and stub twoFactorRedirect response
	describe("TC-AUTH-03: 2FA redirect shows TOTP input", () => {
		beforeEach(() => {
			cy.visit("/#/login");
		});

		it("shows TOTP input when server returns twoFactorRedirect", () => {
			cy.intercept("POST", "**/api/auth/sign-in/email**", {
				statusCode: 200,
				body: {
					twoFactorRedirect: true,
				},
			}).as("signIn2FA");

			cy.findByLabelText(/adresse email|email/i).type(
				Cypress.env("ADMIN_EMAIL") as string,
			);
			cy.findByLabelText(/mot de passe|password/i).type(
				Cypress.env("ADMIN_PASSWORD") as string,
			);
			cy.findByRole("button", { name: /se connecter|sign in/i }).click();

			cy.wait("@signIn2FA");
			cy.findByLabelText(/totp|one-time|code|2fa/i).should("be.visible");
		});
	});

	// TC-AUTH-04: Unauthenticated user visits /students → redirected to /login
	describe("TC-AUTH-04: Unauthenticated redirect", () => {
		beforeEach(() => {
			cy.clearCookies();
			cy.clearLocalStorage();
		});

		it("redirects unauthenticated user from /students to /login", () => {
			cy.visit("/#/students");
			cy.url().should("include", "/login");
		});
	});

	// TC-AUTH-05: Sysadmin logs in → redirected to /sysadmin/, sysadmin nav visible
	describe("TC-AUTH-05: Sysadmin login success", () => {
		beforeEach(() => {
			cy.loginAs("sysadmin");
		});

		it("redirects sysadmin to /sysadmin/ and shows sysadmin navigation", () => {
			cy.visit("/#/sysadmin/");
			cy.url().should("include", "/sysadmin");
			// SysAdminShell has multiple nav elements; check at least one is visible
			cy.findAllByRole("navigation").first().should("be.visible");
			// Sysadmin nav has institution-management links (multiple "institutions" links may exist)
			cy.findAllByRole("link", { name: /institutions/i })
				.first()
				.should("exist");
		});
	});
});
