// Generated by Cypress Author — 2026-09-04

describe("Role-based Redirects & OrgGuard", () => {
	// TC-AUTH-06: Institution admin visiting /sysadmin/ is redirected to /
	describe("TC-AUTH-06: Admin cannot access /sysadmin/", () => {
		beforeEach(() => {
			cy.loginAs("admin");
		});

		it("redirects institution admin away from /sysadmin/ to /", () => {
			cy.visit("/#/sysadmin/");
			cy.url().should("not.include", "/sysadmin");
			cy.url().should("match", /\/$/);
		});
	});

	// TC-OG-01: Unauthenticated user visiting / is redirected to /login
	describe("TC-OG-01: Unauthenticated user is redirected to /login", () => {
		beforeEach(() => {
			cy.clearCookies();
			cy.clearLocalStorage();
		});

		it("redirects unauthenticated user from / to /login", () => {
			cy.visit("/#/");
			cy.url().should("include", "/login");
		});
	});

	// TC-OG-02: Unauthenticated user cannot access protected routes
	describe("TC-OG-02: Unauthenticated user cannot access protected routes", () => {
		beforeEach(() => {
			cy.clearCookies();
			cy.clearLocalStorage();
		});

		it("redirects unauthenticated user from /students to /login", () => {
			cy.visit("/#/students");
			cy.url().should("include", "/login");
		});

		it("redirects unauthenticated user from /classes to /login", () => {
			cy.visit("/#/classes");
			cy.url().should("include", "/login");
		});
	});

	// TC-OG-03: Teacher visiting admin-only pages is forbidden or redirected
	describe("TC-OG-03: Teacher cannot access admin-only pages", () => {
		beforeEach(() => {
			cy.loginAs("teacher");
		});

		it("redirects or shows forbidden when teacher visits /tracks", () => {
			cy.visit("/#/tracks");
			cy.url().then((url) => {
				if (url.includes("/tracks")) {
					cy.findByRole("heading", {
						name: /forbidden|access denied|not allowed|accès refusé/i,
					}).should("be.visible");
				} else {
					expect(url).not.to.include("/tracks");
				}
			});
		});

		it("redirects or shows forbidden when teacher visits /subjects", () => {
			cy.visit("/#/subjects");
			cy.url().then((url) => {
				if (url.includes("/subjects")) {
					cy.findByRole("heading", {
						name: /forbidden|access denied|not allowed|accès refusé/i,
					}).should("be.visible");
				} else {
					expect(url).not.to.include("/subjects");
				}
			});
		});
	});
});
