// Generated by Cypress Author — 2026-09-04
//
// Settings page uses shadcn Tabs (role="tab" on triggers) — NOT NavLinks.
// URL does NOT change when switching settings tabs.

describe("Settings — Profile & Security", () => {
	beforeEach(() => {
		cy.loginAs("admin");
		cy.visit("/#/settings");
		// Settings page uses Better-Auth HTTP API (not tRPC) — no tRPC batching issue here.
		// Wait for the profile form to load.
		cy.findByPlaceholderText(/your name/i, { timeout: 15000 }).should(
			"be.visible",
		);
	});

	// TC-SET-01: Profile tab shows name/email; update name; saved name reflects in sidebar avatar
	it("TC-SET-01: profile form shows name; updated name appears on page after save", () => {
		cy.intercept("POST", "**/api/auth/update-user**").as("updateProfile");

		// Profile tab is active by default — placeholder is visible
		cy.findByPlaceholderText(/your name/i).should("not.have.value", "");

		// Update the name field
		cy.findByPlaceholderText(/your name/i)
			.clear()
			.type("Admin Updated");

		// Submit the profile form
		cy.findByRole("button", { name: /save|update|enregistrer/i })
			.first()
			.click();

		cy.wait("@updateProfile").its("response.statusCode").should("eq", 200);

		// Updated name reflected somewhere on the page (sidebar avatar or header)
		cy.contains(/admin updated/i, { timeout: 8000 }).should("be.visible");
	});

	// TC-SET-02: Change password — correct current password succeeds
	// Stub the real API call to avoid mutating seed data (which would break subsequent tests).
	it("TC-SET-02: change password succeeds with correct current password", () => {
		// Stub the change-password endpoint so the real password is never mutated
		cy.intercept("POST", "**/api/auth/change-password**", {
			statusCode: 200,
			body: { status: true },
		}).as("changePassword");

		// Password change fields — plain password inputs, no htmlFor association
		// eq(0) = current password, eq(1) = new password, eq(2) = confirm new password
		cy.get("input[type='password']")
			.eq(0)
			.type(Cypress.env("ADMIN_PASSWORD") as string);
		cy.get("input[type='password']").eq(1).type("NewPass5678!");
		cy.get("input[type='password']").eq(2).type("NewPass5678!");

		cy.findByRole("button", {
			name: /change password|update password|changer|modifier/i,
		}).click();

		cy.wait("@changePassword").its("response.statusCode").should("eq", 200);

		// Success feedback is shown
		cy.contains(/password changed|mot de passe modifié|updated|changed/i, {
			timeout: 8000,
		}).should("be.visible");
	});

	// TC-SET-03: Security tab — 2FA setup; QR code shown after clicking Enable 2FA
	it("TC-SET-03: security tab shows 2FA setup option and QR code after enable click", () => {
		// Stub the 2FA enable endpoints so we don't require a real TOTP flow
		cy.intercept("POST", "**/auth/two-factor/enable**", {
			statusCode: 200,
			body: { totpURI: "otpauth://totp/test?secret=JBSWY3DPEHPK3PXP" },
		}).as("twoFactorEnable");
		cy.intercept("POST", "**/auth/totp/enable**", {
			statusCode: 200,
			body: { totpURI: "otpauth://totp/test?secret=JBSWY3DPEHPK3PXP" },
		}).as("totpEnable");

		// Settings uses shadcn Tabs — trigger has role="tab". Switching tabs does NOT change URL.
		cy.findByRole("tab", { name: /security|sécurité/i }).click();

		// Security tab content is now active
		cy.findByRole("tab", { name: /security|sécurité/i }).should(
			"have.attr",
			"aria-selected",
			"true",
		);

		// 2FA section should be visible
		cy.contains(/two.factor|2fa|totp/i, { timeout: 10000 }).should(
			"be.visible",
		);

		// Click Enable 2FA button — transitions to inline password setup form
		cy.findByRole("button", {
			name: /enable 2fa|setup totp|activer|enable/i,
		}).click();

		// Password input appears inline (not in a dialog)
		cy.get("input[type='password']", { timeout: 8000 })
			.should("be.visible")
			.type(Cypress.env("ADMIN_PASSWORD") as string);

		// "Continue" submits the password; endpoint is stubbed to return a totpURI
		cy.findByRole("button", { name: /continue|continuer/i }).click();

		// After stub responds, the verify step shows the QR code and manual key
		cy.get("body", { timeout: 10000 }).then(($body) => {
			// img[alt*='qr' i] is invalid in jQuery (no case-insensitive flag).
			// Use data:image src match + canvas + manual text as fallback.
			const hasQr =
				$body.find("img[src*='data:image'], canvas").length > 0 ||
				$body
					.find("img")
					.filter((_i: number, el: HTMLElement) =>
						/qr/i.test(el.getAttribute("alt") ?? ""),
					).length > 0;
			const hasManualKey =
				$body.text().includes("manually") ||
				$body.text().includes("manuellement");
			expect(hasQr || hasManualKey).to.be.true;
		});
	});
});
