// Generated by Cypress Author — 2026-09-04

describe("Attendance", () => {
	beforeEach(() => {
		cy.loginAs("admin");
	});

	// TC-ATT-01: /attendance page loads with heading and class selector
	// Note: the page shows an empty state until a class is selected via the combobox.
	// There is no summary table on initial load — sessions require classId param.
	it("TC-ATT-01: shows attendance page with heading and class selector prompt", () => {
		cy.visit("/#/attendance");

		// Heading is visible
		cy.findByRole("heading", { name: /attendance/i, timeout: 15000 }).should(
			"be.visible",
		);

		// Before a class is selected the page shows a guidance prompt
		cy.contains(/select a class/i).should("be.visible");

		// "New Session" button is always visible
		cy.findByRole("button", { name: /new session/i }).should("be.visible");

		// The class combobox is present
		cy.contains("[role='combobox']", /select class/i).should("exist");
	});

	// TC-ATT-02: "New Session" dialog opens with required form fields
	// Tests the create-session workflow without depending on existing seeded sessions.
	it("TC-ATT-02: New Session dialog opens and shows required form fields", () => {
		cy.visit("/#/attendance");
		cy.findByRole("heading", { name: /attendance/i, timeout: 15000 }).should(
			"be.visible",
		);

		cy.findByRole("button", { name: /new session/i }).click();

		// Dialog is visible
		cy.findByRole("dialog").should("be.visible");

		cy.findByRole("dialog").within(() => {
			// Class combobox
			cy.contains("[role='combobox']", /select class/i).should("exist");
			// Term combobox
			cy.contains("[role='combobox']", /select term/i).should("exist");
			// Create/Cancel buttons
			cy.findByRole("button", { name: /create session|create/i }).should(
				"exist",
			);
			cy.findByRole("button", { name: /cancel/i }).should("exist");
		});

		// Close dialog
		cy.findByRole("button", { name: /cancel/i }).click();
		cy.findByRole("dialog").should("not.exist");
	});
});
