// Generated by Cypress Author — 2026-09-04

describe("Classes", () => {
	beforeEach(() => {
		cy.loginAs("admin");
	});

	// TC-CLS-01: /classes shows "4ème D" with name, level, and student count
	it("TC-CLS-01: shows class list with 4ème D entry", () => {
		cy.visit("/#/classes");
		// tRPC queries are batched — wait for table content instead of cy.wait
		cy.findByRole("table", { timeout: 15000 }).should("be.visible");

		// "4ème D" row must be present
		cy.contains(/4ème D/i).should("be.visible");

		// Level badge appears inside the table
		cy.findByRole("table").within(() => {
			cy.contains(/4[eè]me/i).should("exist");
		});
	});

	// TC-CLS-02: Open "Add class" dialog, fill required fields, save
	it("TC-CLS-02: creates a new class via dialog", () => {
		cy.visit("/#/classes");
		cy.findByRole("table", { timeout: 15000 }).should("be.visible");

		cy.interceptTrpc("classes.create", "createClass");

		cy.findByRole("button", { name: /add class|ajouter/i }).click();
		cy.findByRole("dialog").should("be.visible");

		const ts = Date.now();
		const className = `Cypress ${ts}`;

		// FormField has no htmlFor → findByLabelText fails. Use positional inputs.
		cy.findByRole("dialog").within(() => {
			// Inputs in order: Name (0), Code (1), Level (2)
			cy.get("input:not([type='hidden']):not([type='checkbox'])")
				.eq(0)
				.type(className);
			cy.get("input:not([type='hidden']):not([type='checkbox'])")
				.eq(1)
				.type(`CY${ts.toString().slice(-4)}`);
			cy.get("input:not([type='hidden']):not([type='checkbox'])")
				.eq(2)
				.type("6ème");
		});

		// Academic year: Combobox — click the first combobox in the dialog (academic year)
		cy.findByRole("dialog").within(() => {
			cy.findAllByRole("combobox").first().click();
		});
		// Pick the first option in the dropdown list
		cy.findAllByRole("option").first().click();

		// Submit the form — last button in dialog (not the combobox trigger)
		cy.findByRole("dialog").within(() => {
			cy.findByRole("button", {
				name: /add class|save|create|ajouter|enregistrer/i,
			})
				.last()
				.click();
		});

		cy.wait("@createClass").its("response.statusCode").should("eq", 200);
		cy.findByRole("dialog").should("not.exist");

		// New class appears in the refreshed list
		cy.contains(className, { timeout: 10000 }).should("be.visible");
	});

	// TC-CLS-03: Click "4ème D" → /classes/:id/roster — enrolled students and section heading visible
	it("TC-CLS-03: class roster tab shows enrolled students section", () => {
		cy.visit("/#/classes");
		cy.findByRole("table", { timeout: 15000 }).should("be.visible");

		cy.contains(/4ème D/i).click();

		// Redirects to /classes/:id/roster
		cy.url().should("match", /\/classes\/[^/]+\/roster$/);

		// "Roster" heading is rendered by ClassRoster
		cy.findByRole("heading", { name: /roster|liste/i }).should("be.visible");

		// Either a table with rows, or the empty state message
		cy.get("body").then(($body) => {
			if ($body.find("table tbody tr").length > 0) {
				cy.findByRole("table").should("be.visible");
			} else {
				cy.findByText(/no students enrolled|aucun élève/i).should("be.visible");
			}
		});
	});

	// TC-CLS-04: Switch to Grades tab → /classes/:id/grades — grade matrix or empty state
	it("TC-CLS-04: class grades tab renders", () => {
		cy.visit("/#/classes");
		cy.findByRole("table", { timeout: 15000 }).should("be.visible");

		cy.contains(/4ème D/i).click();
		cy.url().should("match", /\/classes\/[^/]+\/roster$/);

		cy.url().then((url) => {
			const classId = url.match(/\/classes\/([^/]+)\//)?.[1];
			cy.visit(`/#/classes/${classId}/grades`);

			cy.url().should("include", `/classes/${classId}/grades`);

			cy.get("body").should(
				"satisfy",
				($body: JQuery<HTMLBodyElement>) =>
					$body.find("table").length > 0 ||
					$body.text().match(/no subject|aucune matière|grade/i) !== null,
			);
		});
	});

	// TC-CLS-05: Switch to Assignments tab → /classes/:id/assignments
	it("TC-CLS-05: class assignments tab shows subject assignments", () => {
		cy.visit("/#/classes");
		cy.findByRole("table", { timeout: 15000 }).should("be.visible");

		cy.contains(/4ème D/i).click();
		cy.url().should("match", /\/classes\/[^/]+\/roster$/);

		cy.url().then((url) => {
			const classId = url.match(/\/classes\/([^/]+)\//)?.[1];
			cy.visit(`/#/classes/${classId}/assignments`);

			cy.url().should("include", `/classes/${classId}/assignments`);

			// "Subject Assignments" heading from ClassAssignments component
			cy.findByRole("heading", {
				name: /subject assignments|affectations/i,
			}).should("be.visible");

			// "Assign" button is always rendered
			cy.findByRole("button", { name: /^assign$|^affecter$/i }).should(
				"be.visible",
			);

			// Wait for data to load before snapshot
			cy.get("body").should(
				"satisfy",
				($body: JQuery<HTMLBodyElement>) =>
					$body.find("table").length > 0 ||
					$body
						.text()
						.match(/no subjects assigned|aucune matière affectée/i) !== null,
			);

			// Seed guarantees "M. Nkemdirim" is assigned to Maths in 4ème D
			cy.get("body").then(($body) => {
				if ($body.find("table").length > 0) {
					cy.findByText(/mathematics|mathématiques|maths/i).should(
						"be.visible",
					);
				} else {
					cy.findByText(/no subjects assigned|aucune matière affectée/i).should(
						"be.visible",
					);
				}
			});
		});
	});
});
