// Generated by Cypress Author — 2026-09-04

describe("Class Councils", () => {
	beforeEach(() => {
		cy.loginAs("admin");
	});

	// TC-CC-01: /class-councils → existing councils listed with class name and status
	it("TC-CC-01: lists existing class councils with class name and status", () => {
		cy.visit("/#/class-councils");

		// tRPC queries are batched — wait for heading, not cy.wait("@alias")
		cy.findByRole("heading", {
			name: /class councils|conseils de classe/i,
			timeout: 15000,
		}).should("be.visible");

		// At minimum one council row should appear (seeded data has 4ème D)
		cy.contains(/4ème D/i, { timeout: 10000 }).should("be.visible");

		// Status label is present somewhere on the page (open / closed / pending)
		cy.get("body").should(
			"satisfy",
			($body: JQuery<HTMLBodyElement>) =>
				$body.text().match(/open|closed|pending|ouvert|fermé|en attente/i) !==
				null,
		);
	});

	// TC-CC-02: Open a council → student deliberation results shown; decisions can be recorded
	it("TC-CC-02: shows deliberation results and allows recording a decision", () => {
		cy.visit("/#/class-councils");
		cy.findByRole("heading", {
			name: /class councils|conseils de classe/i,
			timeout: 15000,
		}).should("be.visible");

		// Click through to the first council matching the seeded class
		cy.contains(/4ème D/i, { timeout: 10000 }).click();

		// URL should change to detail route
		cy.url().should("match", /\/class-councils\/.+/);

		// Seeded student must appear in the deliberation table
		cy.contains(/Alima Mbarga/i, { timeout: 10000 }).should("be.visible");

		// Decision controls: Combobox — click trigger then pick option (NOT .select())
		cy.findAllByRole("combobox", { timeout: 8000 }).first().should("exist");

		// Intercept the save mutation before triggering it (mutation = POST — cy.wait works)
		cy.interceptTrpc("classCouncils.addDecision", "addDecision");

		// Click the combobox trigger to open options
		cy.findAllByRole("combobox").first().click();

		// Pick the "pass" / "admis" option
		cy.findByRole("option", {
			name: /pass|admis|promou/i,
			timeout: 5000,
		}).click();

		cy.findAllByRole("button", { name: /save|enregistrer|confirm/i })
			.first()
			.click();

		cy.wait("@addDecision")
			.its("response.statusCode")
			.should("be.oneOf", [200, 207]);
	});
});
