// Generated by Cypress Author — 2026-09-04

describe("Finance", () => {
	beforeEach(() => {
		cy.loginAs("admin");
	});

	// TC-FIN-01: /finance shows fee collection summary cards
	// Note: page shows "Finances" heading + summary cards (Total collected, Fee schedules, Payments).
	// There is NO "outstanding" card — the design shows totals, not per-student balances.
	it("TC-FIN-01: shows finance page with summary cards and payments table", () => {
		cy.visit("/#/finance");

		// tRPC queries are batched — wait for heading content, not cy.wait
		cy.findByRole("heading", { name: /finances/i, timeout: 15000 }).should(
			"be.visible",
		);

		// Summary card: Total collected
		cy.findByText(/total collected/i).should("be.visible");

		// Record payment button is always visible
		cy.findByRole("button", { name: /record payment/i }).should("be.visible");

		// Payments table or empty state is rendered
		cy.get("body", { timeout: 10000 }).should(
			"satisfy",
			($body: JQuery<HTMLBodyElement>) =>
				$body.find("table").length > 0 ||
				$body.text().match(/no payments/i) !== null,
		);
	});

	// TC-FIN-02: "Record payment" dialog opens; mutation fires on submit
	// Note: payment method uses shadcn <Select>, not native <select>. Cannot use .select().
	// Student is a Combobox. Labels are NOT connected to inputs via htmlFor.
	it("TC-FIN-02: Record payment dialog opens and closes correctly", () => {
		cy.visit("/#/finance");
		cy.findByRole("heading", { name: /finances/i, timeout: 15000 }).should(
			"be.visible",
		);

		cy.findByRole("button", { name: /record payment/i }).click();

		// Dialog is visible
		cy.findByRole("dialog").should("be.visible");

		cy.findByRole("dialog").within(() => {
			// Dialog heading
			cy.findByText(/record payment/i).should("be.visible");

			// Student combobox (custom Combobox with role="combobox")
			cy.findAllByRole("combobox").should("have.length.gte", 1);

			// Amount input — placeholder is "50000"
			cy.findByPlaceholderText("50000").should("be.visible").type("25000");

			// Cancel button
			cy.findByRole("button", { name: /cancel/i }).should("exist");
		});

		// Close dialog via cancel
		cy.findByRole("dialog").within(() => {
			cy.findByRole("button", { name: /cancel/i }).click();
		});
		cy.findByRole("dialog").should("not.exist");
	});
});
