// Generated by Cypress Author — 2026-09-04

// ─── Navigation helper ────────────────────────────────────────────────────────
// Visits /grades, selects class → subject → term via the selector UI, then
// clicks "Full grid" to land on /grades/:classId/:subjectId/:termId.
function navigateToGradeGrid() {
	cy.visit("/#/grades");

	// tRPC queries are batched — wait for the class selector button to appear
	// PillCombobox trigger shows placeholder "Class…" until data loads
	cy.findByRole("button", { name: /class…/i }, { timeout: 15000 }).should(
		"be.visible",
	);

	// 1. Select class — PillCombobox trigger, placeholder "Class…"
	cy.findByRole("button", { name: /class…/i }).click();
	cy.findByRole("option", { name: /4ème d/i }).click();
	// Wait for URL to update — confirms setSearchParams fired and React re-rendered
	cy.url().should("include", "classId=");

	// 2. Select subject — Popover trigger, enabled after class is chosen
	cy.findByRole(
		"button",
		{ name: /subject…|math/i },
		{ timeout: 8000 },
	).click();
	cy.findByRole("option", { name: /math/i }).click();
	cy.url().should("include", "subjectId=");

	// 3. Select term — PillCombobox, placeholder "Term…" / "Select term…"
	cy.findByRole("button", { name: /term/i }, { timeout: 8000 }).click();
	cy.findByRole("option", { name: /term 1/i }).click();
	cy.url().should("include", "termId=");

	// "Full grid" link appears once all three are chosen — explicit timeout for async state update
	cy.findByRole("link", { name: /full grid/i }, { timeout: 10000 }).click();

	// Confirm we landed on the dedicated grid route
	cy.url().should("match", /\/grades\/[^/]+\/[^/]+\/[^/]+$/);
}

// ─── TC-GRD-05: Selector interface and navigation ────────────────────────────
describe("TC-GRD-05 — Grade entry selector interface", () => {
	beforeEach(() => {
		cy.loginAs("teacher");
	});

	it("TC-GRD-05: /grades shows class/subject/term selectors; selecting all three navigates to grade grid", () => {
		cy.visit("/#/grades");

		// Wait for selectors to load — no cy.wait on aliases (batched queries)
		cy.findByRole("button", { name: /class…/i }, { timeout: 15000 }).should(
			"be.visible",
		);
		cy.findByRole("button", { name: /term…/i }).should("be.visible");
		// Subject selector (disabled until class is chosen)
		cy.findByRole("button", { name: /select class first/i }).should(
			"be.visible",
		);

		// "Full grid" link is absent until all three are selected
		cy.findByRole("link", { name: /full grid/i }).should("not.exist");

		// Select class
		cy.findByRole("button", { name: /class…/i }).click();
		cy.findByRole("option", { name: /4ème d/i }).click();
		cy.url().should("include", "classId=");

		// Subject selector is now enabled
		cy.findByRole(
			"button",
			{ name: /subject…|math/i },
			{ timeout: 8000 },
		).click();
		cy.findByRole("option", { name: /math/i }).click();
		cy.url().should("include", "subjectId=");

		// Select term
		cy.findByRole("button", { name: /term/i }, { timeout: 8000 }).click();
		cy.findByRole("option", { name: /term 1/i }).click();
		cy.url().should("include", "termId=");

		// "Full grid" link appears and clicking it navigates to the grade grid
		cy.findByRole("link", { name: /full grid/i }, { timeout: 10000 })
			.should("be.visible")
			.click();

		cy.url().should("match", /\/grades\/[^/]+\/[^/]+\/[^/]+$/);
	});
});

// ─── TC-GRD-01 to TC-GRD-04: Grade grid operations ──────────────────────────
describe("Grade grid (TC-GRD-01 to TC-GRD-04)", () => {
	beforeEach(() => {
		cy.loginAs("teacher");
		navigateToGradeGrid();
	});

	// TC-GRD-01: Grade grid shows student rows with editable assessment columns
	it("TC-GRD-01: grade grid shows students × assessment columns with editable inputs", () => {
		cy.findByText(/grade grid/i).should("be.visible");

		cy.findByRole("table").should("be.visible");

		cy.findByRole("table").within(() => {
			cy.findByText(/mbarga/i).should("be.visible");
		});

		cy.findByRole("table").within(() => {
			cy.findAllByRole("columnheader").should("have.length.gte", 2);
		});

		cy.findAllByRole("spinbutton").should("have.length.gte", 1);
		cy.findAllByRole("spinbutton").first().should("not.be.disabled");
	});

	// TC-GRD-02: Enter valid score, save, reload — value persists
	it("TC-GRD-02: entering a grade, saving, and reloading persists the value", () => {
		cy.interceptTrpc("assessments.batchUpsert", "saveGrades");

		cy.findAllByRole("spinbutton").first().clear().type("15");

		cy.findByRole("button", { name: /^save/i }).click();

		cy.wait("@saveGrades").its("response.statusCode").should("eq", 200);

		cy.findByRole("button", { name: /saved/i }).should("be.visible");

		cy.reload();
		cy.findAllByRole("spinbutton").first().should("have.value", "15");
	});

	// TC-GRD-03: Out-of-range scores (> 20, < 0) trigger HTML5 validation
	it("TC-GRD-03: out-of-range scores (>20, <0) mark the input as invalid", () => {
		cy.findAllByRole("spinbutton")
			.first()
			.clear()
			.type("25")
			.should(($el) => {
				expect(($el[0] as HTMLInputElement).validity.valid).to.be.false;
				expect(($el[0] as HTMLInputElement).validity.rangeOverflow).to.be.true;
			});

		cy.findAllByRole("spinbutton")
			.first()
			.clear()
			.type("-1")
			.should(($el) => {
				expect(($el[0] as HTMLInputElement).validity.valid).to.be.false;
				expect(($el[0] as HTMLInputElement).validity.rangeUnderflow).to.be.true;
			});
	});

	// TC-GRD-04: Comments page — enter a comment, save, reload — comment persists
	it("TC-GRD-04: teacher comments are saved and persist after reload", () => {
		cy.findByRole("button", { name: /comments/i }).click();

		cy.url().should("match", /\/grades\/[^/]+\/[^/]+\/[^/]+\/comments$/);

		cy.findByText(/teacher comments/i).should("be.visible");

		cy.findAllByRole("textbox").should("have.length.gte", 1);

		cy.interceptTrpc("comments.batchUpsert", "saveComments");
		cy.findAllByRole("textbox")
			.first()
			.clear()
			.type("Good progress this term.");

		cy.findByRole("button", { name: /^save/i }).click();

		cy.wait("@saveComments").its("response.statusCode").should("eq", 200);

		cy.findByRole("button", { name: /saved/i }).should("be.visible");

		cy.reload();
		cy.findAllByRole("textbox")
			.first()
			.should("have.value", "Good progress this term.");
	});
});
