// Generated by Cypress Author — 2026-09-04

describe("Official Exams", () => {
	beforeEach(() => {
		cy.loginAs("admin");
	});

	// TC-OE-01: /official-exams → exam sessions listed (BEPC, BAC, etc.) or empty state
	it("TC-OE-01: shows official exams page with heading and content area", () => {
		cy.visit("/#/official-exams");

		// tRPC queries are batched — wait for heading, not cy.wait("@alias")
		cy.findByRole("heading", {
			name: /official exams/i,
			timeout: 15000,
		}).should("be.visible");

		// "New session" button is always visible
		cy.findByRole("button", { name: /new session/i }).should("be.visible");

		// Either a table with data or the empty state message is shown
		cy.get("body", { timeout: 10000 }).should(
			"satisfy",
			($body: JQuery<HTMLBodyElement>) =>
				$body.find("[role='table']").length > 0 ||
				$body.text().match(/no sessions configured|aucun/i) !== null,
		);
	});

	// TC-OE-02: "New session" button navigates to /official-exams/new (a full form page)
	// Note: NOT a dialog — the button calls navigate("/official-exams/new")
	it("TC-OE-02: navigates to new exam session form", () => {
		cy.visit("/#/official-exams");
		cy.findByRole("heading", {
			name: /official exams/i,
			timeout: 15000,
		}).should("be.visible");

		cy.findByRole("button", { name: /new session/i }).click();

		// Should navigate to the new session form page (not open a dialog)
		cy.url().should("include", "/official-exams/new");

		// Form page heading is visible
		cy.findByRole("heading", {
			name: /create exam session|new exam session/i,
			timeout: 10000,
		}).should("be.visible");

		// Exam type selector is present (shadcn Select renders as role="combobox")
		cy.findByRole("combobox").should("exist");
	});

	// TC-OE-03: Clicking "Candidates" button navigates to the detail/candidates page
	// Skips gracefully when no sessions are seeded.
	it("TC-OE-03: shows candidates list when exam session exists", () => {
		cy.visit("/#/official-exams");
		cy.findByRole("heading", {
			name: /official exams/i,
			timeout: 15000,
		}).should("be.visible");

		cy.get("body", { timeout: 10000 }).then(($body) => {
			const hasRows = $body.find("[role='table'] tbody tr").length > 0;
			if (!hasRows) {
				// No seeded data — skip the navigation step
				cy.log("No exam sessions seeded — skipping navigation test");
				return;
			}

			// Click the "Candidates" button in the first row to navigate to detail
			cy.findByRole("table").within(() => {
				cy.findByRole("button", { name: /candidates/i })
					.first()
					.click();
			});

			cy.url().should("match", /\/official-exams\/[^/]+/);

			// Candidates tab link is visible on the detail page
			cy.findByRole("link", { name: /candidates/i }).should("exist");
		});
	});

	// TC-OE-04: Results tab loads on exam detail page
	it("TC-OE-04: shows results page when navigating to an exam session", () => {
		cy.visit("/#/official-exams");
		cy.findByRole("heading", {
			name: /official exams/i,
			timeout: 15000,
		}).should("be.visible");

		cy.get("body", { timeout: 10000 }).then(($body) => {
			const hasRows = $body.find("[role='table'] tbody tr").length > 0;
			if (!hasRows) {
				cy.log("No exam sessions seeded — skipping navigation test");
				return;
			}

			cy.findByRole("table").within(() => {
				cy.findByRole("button", { name: /candidates/i })
					.first()
					.click();
			});

			cy.url().should("match", /\/official-exams\/[^/]+/);

			cy.findByRole("link", { name: /results/i }).click();
			cy.url().should("include", "/results");

			// Results page renders some content
			cy.get("body", { timeout: 8000 }).should(
				"satisfy",
				($body: JQuery<HTMLBodyElement>) => $body.text().match(/\d+/) !== null,
			);
		});
	});

	// TC-OE-05: Settings tab shows editable form for exam session
	it("TC-OE-05: allows editing exam session settings", () => {
		cy.visit("/#/official-exams");
		cy.findByRole("heading", {
			name: /official exams/i,
			timeout: 15000,
		}).should("be.visible");

		cy.get("body", { timeout: 10000 }).then(($body) => {
			const hasRows = $body.find("[role='table'] tbody tr").length > 0;
			if (!hasRows) {
				cy.log("No exam sessions seeded — skipping navigation test");
				return;
			}

			cy.findByRole("table").within(() => {
				cy.findByRole("button", { name: /candidates/i })
					.first()
					.click();
			});

			cy.url().should("match", /\/official-exams\/[^/]+/);

			cy.findByRole("link", { name: /settings/i }).click();
			cy.url().should("include", "/settings");

			cy.interceptTrpc("officialExams.updateSession", "updateExam");

			// Center code or session year input — edit it
			cy.get("input[type='number'], input[type='text']", { timeout: 8000 })
				.first()
				.clear()
				.type("2026");

			cy.findByRole("button", { name: /save|update|enregistrer/i }).click();

			cy.wait("@updateExam")
				.its("response.statusCode")
				.should("be.oneOf", [200, 207]);
		});
	});
});
