// Generated by Cypress Author — 2026-09-04

describe("Report Cards", () => {
	beforeEach(() => {
		cy.loginAs("admin");
	});

	// TC-RC-01: /report-cards shows list of classes with report card status
	it("TC-RC-01: shows list of classes with their report card status", () => {
		cy.visit("/#/report-cards");
		// tRPC queries are batched — wait for content instead of cy.wait("@alias")
		cy.findByRole("heading", {
			name: /report cards?|bulletins?/i,
			timeout: 15000,
		}).should("be.visible");

		// At least one class row rendered
		cy.findAllByRole("row", { timeout: 10000 }).should("have.length.gte", 2);

		// Class name and status are visible in the first data row
		cy.findAllByRole("row")
			.not(":first")
			.first()
			.within(() => {
				cy.findByText(/4ème D|classe|class/i).should("exist");
				cy.findByText(
					/generated|pending|draft|généré|brouillon|en attente/i,
				).should("exist");
			});
	});

	// TC-RC-02: Select "4ème D" and a term → student rows with averages
	it("TC-RC-02: selecting 4ème D and a term shows each student with averages", () => {
		cy.visit("/#/report-cards");
		cy.findByRole("heading", {
			name: /report cards?|bulletins?/i,
			timeout: 15000,
		}).should("be.visible");

		// Click on "4ème D" class entry
		cy.contains(/4ème D|4eme D/i, { timeout: 10000 }).click();

		// A term selector should appear — use native select or combobox
		cy.get("select, [role='combobox']", { timeout: 10000 })
			.first()
			.then(($el) => {
				if ($el.is("select")) {
					cy.wrap($el)
						.find("option")
						.eq(1)
						.then(($opt) => {
							const value = $opt.val() as string;
							cy.wrap($el).select(value);
						});
				} else {
					cy.wrap($el).click();
					cy.findAllByRole("option").eq(1).click();
				}
			});

		// URL now contains classId and termId segments
		cy.url().should("match", /\/report-cards\/.+\/.+/, { timeout: 10000 });

		// Wait for student data to load before iterating rows
		cy.contains(/alima mbarga/i, { timeout: 10000 }).should("be.visible");

		// Student rows must include an average value
		cy.findAllByRole("row", { timeout: 10000 })
			.not(":first")
			.should("have.length.gte", 1)
			.each(($row) => {
				cy.wrap($row)
					.invoke("text")
					.should("match", /\d+[.,]\d+|—|-/);
			});
	});

	// TC-RC-03: Clicking a student's report card shows print-ready preview
	it("TC-RC-03: clicking a student report card shows print-ready preview with grades and comments", () => {
		cy.visit("/#/report-cards");
		cy.findByRole("heading", {
			name: /report cards?|bulletins?/i,
			timeout: 15000,
		}).should("be.visible");

		cy.contains(/4ème D|4eme D/i, { timeout: 10000 }).click();

		cy.get("select, [role='combobox']", { timeout: 10000 })
			.first()
			.then(($el) => {
				if ($el.is("select")) {
					cy.wrap($el)
						.find("option")
						.eq(1)
						.then(($opt) => {
							cy.wrap($el).select($opt.val() as string);
						});
				} else {
					cy.wrap($el).click();
					cy.findAllByRole("option").eq(1).click();
				}
			});

		cy.url().should("match", /\/report-cards\/.+\/.+/, { timeout: 10000 });

		// Click the "View" or report-card link for the first student
		cy.findAllByRole(
			"link",
			{ name: /view|voir|bulletin/i },
			{ timeout: 10000 },
		)
			.first()
			.click();

		// URL is the individual report card detail
		cy.url().should("match", /\/report-cards\/.+/);

		// Print-ready layout: student name visible
		cy.contains(/alima mbarga/i, { timeout: 10000 }).should("be.visible");

		// Subject "Mathématiques" and its grade appear
		cy.contains(/math[eé]matiques/i).should("be.visible");

		// Average section is present
		cy.contains(/moyenne|average/i).should("be.visible");

		// Comments or appreciation section
		cy.contains(/comment|appréciation|observation/i).should("be.visible");

		// A print button should exist for print-ready views
		cy.findByRole("button", { name: /print|imprimer/i }).should("exist");
	});
});
