// Generated by Cypress Author — 2026-09-04

describe("Staff Management", () => {
	beforeEach(() => {
		cy.loginAs("admin");
		cy.visit("/#/staff");
		// tRPC queries are batched — wait for table content instead of cy.wait("@alias")
		cy.findByRole("table", { timeout: 15000 }).should("be.visible");
	});

	// TC-STF-01: Staff list shows M. Nkemdirim with name, role (teacher)
	it("TC-STF-01: staff list shows M. Nkemdirim with name and teacher role", () => {
		cy.findByRole("table").should("be.visible");

		// Seed staff member row is present
		cy.findByRole("table").within(() => {
			cy.findByText(/nkemdirim/i).should("be.visible");

			// Role badge shows "Teacher" — anchored regex avoids matching email
			cy.findByText(/^teacher$/i).should("be.visible");
		});
	});

	// TC-STF-02: Open "Add staff member" dialog, fill form, save → member appears in list
	it("TC-STF-02: adds a new staff member via dialog and shows in list", () => {
		cy.interceptTrpc("staff.create", "createStaff");

		cy.findByRole("button", { name: /add staff member/i }).click();

		cy.findByRole("dialog").should("be.visible");
		cy.findByRole("dialog").within(() => {
			cy.findByText(/add staff member/i).should("be.visible");

			// Fill textboxes in order: first name, last name, email
			cy.findAllByRole("textbox").first().clear().type("Sophie");
			cy.findAllByRole("textbox").eq(1).clear().type("Ekanga");
			cy.findAllByRole("textbox")
				.eq(2)
				.clear()
				.type("sophie.ekanga@test.local");

			// Set role to Teacher via the Select combobox
			cy.findByRole("combobox").click();
		});

		// Options render outside the dialog — pick "Teacher"
		cy.findByRole("option", { name: /^teacher$/i }).click();

		cy.findByRole("dialog").within(() => {
			cy.findByRole("button", { name: /^save$|^create$|^add$/i }).click();
		});

		cy.wait("@createStaff").its("response.statusCode").should("eq", 200);

		// Dialog closes
		cy.findByRole("dialog").should("not.exist");

		// New member appears in the table — cy.contains avoids multi-match
		cy.contains(/ekanga/i).should("be.visible");
	});

	// TC-STF-03: Clicking staff member navigates to profile tab with personal info
	it("TC-STF-03: clicking M. Nkemdirim opens profile with personal info and role", () => {
		cy.findByRole("table").within(() => {
			cy.findByRole("link", { name: /nkemdirim/i }).click();
		});

		// Wait for profile page to load (URL and content)
		cy.url().should("match", /\/staff\/[^/]+\/profile/, { timeout: 15000 });

		// Profile shows personal info
		cy.contains(/nkemdirim/i, { timeout: 10000 }).should("be.visible");

		// Role badge is visible
		cy.findByText(/teacher/i).should("be.visible");

		// Email field is present
		cy.get("body").invoke("text").should("match", /@/);
	});

	// TC-STF-04: Assignments tab for M. Nkemdirim shows classes and subjects
	it("TC-STF-04: assignments tab shows classes and subjects for M. Nkemdirim", () => {
		cy.findByRole("table").within(() => {
			cy.findByRole("link", { name: /nkemdirim/i }).click();
		});

		cy.url().should("match", /\/staff\/[^/]+\/profile/, { timeout: 15000 });

		// Switch to the Assignments tab — use last() to avoid matching sidebar nav link
		cy.findAllByRole("link", { name: /assignments?/i }, { timeout: 10000 })
			.last()
			.click();

		cy.url().should("match", /\/staff\/[^/]+\/assignments/);

		// Assignments table is visible with subject and class columns
		cy.findByRole("table", { timeout: 15000 }).should("be.visible");
		cy.findByRole("table").within(() => {
			cy.findByRole("columnheader", { name: /subject/i }).should("be.visible");
			cy.findByRole("columnheader", { name: /class/i }).should("be.visible");

			// At least one assignment row for Maths / 4ème D
			cy.findByText(/math/i).should("exist");
		});
	});
});
