// Generated by Cypress Author — 2026-09-04

describe("Students", () => {
	beforeEach(() => {
		cy.loginAs("admin");
	});

	// TC-STU-01: /students renders the list (or empty state) + "Add student" button
	it("TC-STU-01: shows students page with Add student button", () => {
		cy.visit("/#/students");
		// tRPC queries are batched — wait for content instead of cy.wait("@alias")
		cy.get("body", { timeout: 15000 }).should("exist");

		// "Add student" button is always visible regardless of list state
		cy.findByRole(
			"button",
			{ name: /add student|new student|ajouter|nouvel élève/i },
			{ timeout: 10000 },
		).should("be.visible");

		// Either a table row or the empty-state message must be present
		// shadcn DataTable renders <table> without explicit role="table" — use $body.find('table')
		cy.get("body").then(($body) => {
			if ($body.find("table").length) {
				cy.findByRole("table").should("be.visible");
			} else {
				cy.findByText(/no students|aucun élève/i).should("be.visible");
			}
		});
	});

	// TC-STU-02: Click "Add student" → dialog opens; fill minimum fields; submit
	it("TC-STU-02: creates a new student via dialog", () => {
		cy.visit("/#/students");
		cy.findByRole(
			"button",
			{ name: /add student|new student|ajouter|nouvel élève/i },
			{ timeout: 10000 },
		).should("be.visible");

		cy.interceptTrpc("students.create", "createStudent");

		cy.findByRole("button", {
			name: /add student|new student|ajouter|nouvel élève/i,
		}).click();

		// Dialog is open
		cy.findByRole("dialog").should("be.visible");

		const ts = Date.now();
		// FormField has no htmlFor → findByLabelText fails. Use placeholder or positional.
		cy.findByRole("dialog").within(() => {
			// First visible text input = First name, second = Last name
			cy.get("input:not([type='hidden']):not([type='checkbox'])")
				.eq(0)
				.type(`Cypress${ts}`);
			cy.get("input:not([type='hidden']):not([type='checkbox'])")
				.eq(1)
				.type("TestStudent");
		});

		// Gender: Combobox trigger — click the first combobox in the dialog
		cy.findByRole("dialog").within(() => {
			cy.findAllByRole("combobox").first().click();
		});
		cy.findByRole("option", { name: /^male$|^masculin$/i }).click();

		// Click the submit button BEFORE waiting for the mutation
		cy.findByRole("button", { name: /save|add|create|enregistrer|créer/i })
			.last()
			.click();

		cy.wait("@createStudent").its("response.statusCode").should("eq", 200);

		// Dialog closes on success
		cy.findByRole("dialog").should("not.exist");
	});

	// TC-STU-03: Type partial name in search → only matching rows shown
	it("TC-STU-03: search filters the student list", () => {
		cy.visit("/#/students");
		cy.findByRole(
			"button",
			{ name: /add student|new student|ajouter|nouvel élève/i },
			{ timeout: 10000 },
		).should("be.visible");

		// Locate the search input by placeholder
		cy.findByPlaceholderText(/search by name|rechercher/i).type("Ali");

		// Every visible student link should contain "Ali"
		cy.findAllByRole("link", { timeout: 10000 }).each(($link) => {
			const text = $link.text();
			// Filter only student-name links (they navigate to /students/:id)
			// HashRouter: links are href="#/students/:id"
			if ($link.attr("href")?.includes("/students/")) {
				expect(text.toLowerCase()).to.include("ali");
			}
		});
	});

	// TC-STU-04: Click "Alima Mbarga" → profile tab shows name, DOB, gender and Edit button
	it("TC-STU-04: student profile tab shows personal details", () => {
		cy.visit("/#/students");
		cy.findByRole(
			"button",
			{ name: /add student|new student|ajouter|nouvel élève/i },
			{ timeout: 10000 },
		).should("be.visible");

		cy.contains(/alima mbarga/i, { timeout: 10000 }).click();

		// Wait for detail page: URL should be /students/:id/profile or /students/:id
		cy.url().should("match", /\/students\/[^/]+/);

		// Name is displayed in heading
		cy.contains(/alima/i, { timeout: 10000 }).should("be.visible");

		// Edit / Enroll button is present
		cy.findByRole("button", { name: /enroll|inscrire/i }).should("be.visible");
	});

	// TC-STU-05 – TC-STU-07: Navigate to Grades, Fees, Attendance tabs via URL
	it("TC-STU-05: grades tab loads for student", () => {
		cy.visit("/#/students");
		cy.findByRole(
			"button",
			{ name: /add student|new student|ajouter|nouvel élève/i },
			{ timeout: 10000 },
		).should("be.visible");

		cy.contains(/alima mbarga/i, { timeout: 10000 }).click();
		cy.url().should("match", /\/students\/[^/]+/);

		cy.url().then((url) => {
			const studentId = url.match(/\/students\/([^/]+)/)?.[1];
			cy.visit(`/#/students/${studentId}/grades`);

			cy.url().should("include", `/students/${studentId}/grades`);

			// Either grade rows or an empty-state message
			cy.get("body").then(($body) => {
				const hasGrades = $body.find("table").length > 0;
				if (!hasGrades) {
					cy.findByText(/no grades|aucune note/i).should("be.visible");
				} else {
					cy.findByRole("table").should("be.visible");
				}
			});
		});
	});

	it("TC-STU-06: fees tab loads for student", () => {
		cy.visit("/#/students");
		cy.findByRole(
			"button",
			{ name: /add student|new student|ajouter|nouvel élève/i },
			{ timeout: 10000 },
		).should("be.visible");

		cy.contains(/alima mbarga/i, { timeout: 10000 }).click();
		cy.url().should("match", /\/students\/[^/]+/);

		cy.url().then((url) => {
			const studentId = url.match(/\/students\/([^/]+)/)?.[1];
			cy.visit(`/#/students/${studentId}/fees`);

			cy.url().should("include", `/students/${studentId}/fees`);

			// Fees tab header or empty state
			cy.get("body").should(
				"satisfy",
				($body: JQuery<HTMLBodyElement>) =>
					$body.find("table").length > 0 ||
					$body.text().match(/no fees|aucun frais|fee/i) !== null,
			);
		});
	});

	it("TC-STU-07: attendance tab loads for student", () => {
		cy.visit("/#/students");
		cy.findByRole(
			"button",
			{ name: /add student|new student|ajouter|nouvel élève/i },
			{ timeout: 10000 },
		).should("be.visible");

		cy.contains(/alima mbarga/i, { timeout: 10000 }).click();
		cy.url().should("match", /\/students\/[^/]+/);

		cy.url().then((url) => {
			const studentId = url.match(/\/students\/([^/]+)/)?.[1];
			cy.visit(`/#/students/${studentId}/attendance`);

			cy.url().should("include", `/students/${studentId}/attendance`);

			cy.get("body").should(
				"satisfy",
				($body: JQuery<HTMLBodyElement>) =>
					$body.find("table").length > 0 ||
					$body.text().match(/no attendance|aucune absence|attendance/i) !==
						null,
			);
		});
	});
});
