// Generated by Cypress Author — 2026-09-04

describe("Subjects", () => {
	beforeEach(() => {
		cy.loginAs("admin");
		cy.visit("/#/subjects");
		// tRPC queries are batched — wait for table content instead of cy.wait("@alias")
		cy.findByRole("table", { timeout: 15000 }).should("be.visible");
	});

	// TC-SUBJ-01: Subjects list shows "Mathématiques" with its name visible
	it("TC-SUBJ-01: shows Mathématiques in the subjects list", () => {
		cy.findByRole("table").should("be.visible");

		// Verify Mathématiques row is present
		cy.contains("Mathématiques").should("be.visible");

		// Verify the table has at least the name and code columns
		cy.findByRole("table").within(() => {
			cy.findByRole("columnheader", { name: /subject/i }).should("exist");
			cy.findByRole("columnheader", { name: /code/i }).should("exist");
		});
	});

	// TC-SUBJ-02: Create a new subject via dialog; intercept subjects.create
	it("TC-SUBJ-02: creates a new subject via the New Subject dialog", () => {
		cy.interceptTrpc("subjects.create", "createSubject");

		// Open the create dialog
		cy.findByRole("button", { name: /add subject/i }).click();
		cy.findByRole("dialog").should("be.visible");

		const timestamp = Date.now();
		const subjectName = `Physics ${timestamp}`;
		const subjectCode = `PHY-${timestamp}`.slice(0, 30);

		// Fill in the form
		cy.findByLabelText(/subject name.*en/i)
			.clear()
			.type(subjectName);
		cy.findAllByLabelText(/code/i).first().clear().type(subjectCode);

		// Submit
		cy.findByRole("button", { name: /add subject/i })
			.last()
			.click();

		cy.wait("@createSubject").its("response.statusCode").should("eq", 200);

		// Dialog closes
		cy.findByRole("dialog").should("not.exist");

		// New subject appears in the list
		cy.contains(subjectName).should("be.visible");
	});

	// TC-SUBJ-03: Edit Mathématiques; change subject group; intercept subjects.update
	it("TC-SUBJ-03: edits Mathématiques and saves the updated data", () => {
		cy.interceptTrpc("subjects.update", "updateSubject");

		// Click the Edit button for Mathématiques
		cy.contains("Mathématiques")
			.closest("tr")
			.within(() => {
				cy.findByRole("button", { name: /edit/i }).click();
			});

		cy.findByRole("dialog").should("be.visible");

		// Change the subject group field
		cy.findByLabelText(/subject group/i)
			.clear()
			.type("Sciences");

		// Save
		cy.findByRole("button", { name: /save/i }).click();

		cy.wait("@updateSubject").its("response.statusCode").should("eq", 200);

		// Dialog closes after save
		cy.findByRole("dialog").should("not.exist");
	});

	// TC-SUBJ-04: Delete a subject via confirmation dialog; intercept subjects.delete
	it("TC-SUBJ-04: deletes a subject after confirmation", () => {
		cy.interceptTrpc("subjects.delete", "deleteSubject");

		cy.findByRole("table").within(() => {
			cy.findAllByRole("row").not(":first").first().as("targetRow");
		});

		cy.get("@targetRow").then(($row) => {
			// jQuery does NOT support case-insensitive attribute selectors ([attr*='val' i]).
			// Use .filter() with a JS regex instead.
			const $deleteBtn = $row
				.find("button[aria-label]")
				.filter((_i: number, el: HTMLElement) =>
					/delete|supprimer/i.test(el.getAttribute("aria-label") ?? ""),
				);
			if ($deleteBtn.length) {
				cy.wrap($deleteBtn.first()).click();
			} else {
				cy.wrap($row).within(() => {
					cy.findByRole("button", { name: /edit/i }).click();
				});
				cy.findByRole("dialog").within(() => {
					cy.findByRole("button", { name: /delete|supprimer/i }).click();
				});
			}
		});

		// Dialog opens — may not have an accessible name, just check it's visible
		cy.findByRole("dialog").should("be.visible");

		cy.findByRole("button", { name: /confirm|delete|yes|oui/i })
			.last()
			.click();

		cy.wait("@deleteSubject").its("response.statusCode").should("eq", 200);

		cy.findByRole("dialog").should("not.exist");
	});
});
