// Generated by Cypress Author — 2026-09-04

describe("Tracks", () => {
	beforeEach(() => {
		cy.loginAs("admin");
		cy.visit("/#/tracks");
		// tRPC queries are batched — wait for table content instead of cy.wait("@alias")
		cy.findByRole("table", { timeout: 15000 }).should("be.visible");
	});

	// TC-TRK-01: Tracks list shows existing tracks with name and cycle badge
	it("TC-TRK-01: shows existing tracks listed with name and cycle level", () => {
		cy.findByRole("table").should("be.visible");

		// Column headers: Track, Code, Cycle
		cy.findByRole("table").within(() => {
			cy.findByRole("columnheader", { name: /track/i }).should("exist");
			cy.findByRole("columnheader", { name: /code/i }).should("exist");
			cy.findByRole("columnheader", { name: /cycle/i }).should("exist");
		});

		// Seed track "Série D – Sciences" must be in the list
		cy.contains("Série D – Sciences").should("be.visible");

		// Every non-header row should have a link (track name)
		cy.findByRole("table").within(() => {
			cy.findAllByRole("row")
				.not(":first")
				.each(($row) => {
					cy.wrap($row).within(() => {
						cy.findByRole("link").should("exist");
					});
				});
		});
	});

	// TC-TRK-02: Navigate to "Série D – Sciences" detail; verify coefficient matrix
	it("TC-TRK-02: shows subject-coefficient matrix for Série D – Sciences and allows updating a coefficient", () => {
		// Click the track link — tRPC queries load automatically
		cy.contains("Série D – Sciences").click();

		// URL should include /tracks/:id
		cy.url().should("match", /\/tracks\/[^/]+$/);

		// Wait for track detail content to load (no cy.wait on aliases — queries are batched)
		cy.findByRole("heading", { level: 1, timeout: 15000 })
			.invoke("text")
			.should("match", /série d|sciences/i);

		// Coefficient matrix table is rendered
		cy.findByRole("table", { timeout: 10000 }).should("be.visible");
		cy.findByRole("table").within(() => {
			cy.findByRole("columnheader", { name: /subject/i }).should("exist");
			cy.findByRole("columnheader", { name: /coefficient/i }).should("exist");
		});

		// "Mathématiques" row should be visible with its coefficient input
		cy.contains(/mathématiques/i)
			.closest("tr")
			.within(() => {
				cy.findByRole("spinbutton").should("exist").and("have.value", "4");
			});

		// Update coefficient: change Mathématiques from 4 to 5
		cy.interceptTrpc("tracks.upsertCoefficient", "upsertCoeff");

		cy.contains(/mathématiques/i)
			.closest("tr")
			.within(() => {
				cy.findByRole("spinbutton").clear().type("5");
			});

		// Save the coefficient matrix
		cy.findByRole("button", { name: /save coefficients/i }).click();

		cy.wait("@upsertCoeff").its("response.statusCode").should("eq", 200);

		// Confirmation text appears after save
		cy.findByText(/coefficients saved/i).should("be.visible");
	});
});
