// Generated by Cypress Author — 2026-09-04
// Type declarations for custom Cypress commands

declare global {
	namespace Cypress {
		interface Chainable {
			loginAs(role: "sysadmin" | "admin" | "teacher"): Chainable<void>;
			interceptTrpc(procedure: string, alias: string): Chainable<void>;
		}
	}
}

export {};
