// Generated by Cypress Author — 2026-09-04
//
// Key technical note:
// tRPC QUERIES use GET requests via httpBatchLink (e.g. /trpc/institutions.get?batch=1).
// cy.intercept("POST", "/trpc/institutions.get**") would NEVER match a GET query.
// The query stubs below use method-agnostic intercepts (no "POST" argument).
// Only MUTATIONS (create, update, bulkCreate, etc.) keep the "POST" argument.

describe("Onboarding Wizard", () => {
	/**
	 * Stub institution-state queries to return empty/unconfigured responses.
	 * Must be called BEFORE cy.visit so the intercepts are registered first.
	 * All query stubs are method-agnostic (no "POST") because queries use GET.
	 */
	function stubFreshInstitution() {
		// Institution has no name set → Step 1 shows the full form
		cy.intercept("**/trpc/institutions.get**", {
			statusCode: 200,
			body: [
				{
					result: {
						data: {
							id: "inst-stub",
							name: "",
							type: null,
							city: null,
							logoUrl: null,
							minesecCode: null,
							address: null,
							phone: null,
							email: null,
						},
					},
				},
			],
		});

		// No academic years → Step 2 shows the creation form
		cy.intercept("**/trpc/academicYears.list**", {
			statusCode: 200,
			body: [{ result: { data: [] } }],
		});

		// No tracks → Step 3 shows pre-filled MINESEC table
		cy.intercept("**/trpc/tracks.list**", {
			statusCode: 200,
			body: [{ result: { data: { items: [], total: 0 } } }],
		});

		// No subjects → Step 4 shows pre-filled default table
		cy.intercept("**/trpc/subjects.list**", {
			statusCode: 200,
			body: [{ result: { data: { items: [], total: 0 } } }],
		});

		// No classes → Step 6 shows the add-class form
		cy.intercept("**/trpc/classes.list**", {
			statusCode: 200,
			body: [{ result: { data: { items: [], total: 0 } } }],
		});

		// No staff → Step 7 shows the add-staff form
		cy.intercept("**/trpc/staff.list**", {
			statusCode: 200,
			body: [{ result: { data: { items: [], total: 0 } } }],
		});
	}

	beforeEach(() => {
		cy.clearCookies();
		cy.clearLocalStorage();

		// Log in FIRST — cy.session must not be disrupted by stubs
		cy.loginAs("admin");

		// Register stubs AFTER loginAs so they don't intercept OrgGuard/AppShell queries
		stubFreshInstitution();

		cy.visit("/#/onboarding");
	});

	// TC-OB-01: /onboarding renders with Step 1 Institution Profile active
	it("TC-OB-01: /onboarding renders with Step 1 Institution Profile active", () => {
		// Stubs registered in beforeEach keep the onboarding page visible
		cy.url({ timeout: 15000 }).should("include", "/onboarding");
		cy.contains(/institution setup/i).should("be.visible");

		cy.findByRole("heading", { name: /institution profile/i }).should(
			"be.visible",
		);

		// Step progress indicator: "Step 1 of 7" — check any element
		cy.contains(/step 1 of 7/i).should("be.visible");
	});

	// TC-OB-02: Step 1 — validation error without name; valid data advances to Step 2
	it("TC-OB-02: Step 1 — validation error without name; valid data advances to Step 2", () => {
		cy.intercept("POST", "**/trpc/institutions.update**", {
			statusCode: 200,
			body: [
				{
					result: {
						data: { id: "inst-stub", name: "École Test de Yaoundé" },
					},
				},
			],
		}).as("updateInstitution");

		// Attempt to submit without filling the required Name field
		cy.findByRole("button", { name: /next|suivant/i }).click();

		// Validation error for the Name field must appear
		cy.findByText(/required/i).should("be.visible");

		// Fill valid school name
		cy.findByPlaceholderText(/lycée de yaoundé/i).type("École Test de Yaoundé");

		// Select institution type — Lycée radio / label
		cy.findByText(/^lycée$/i).click();

		// Fill city
		cy.findByPlaceholderText(/yaoundé, mfoundi/i).type("Yaoundé");

		// Submit — triggers institutions.update
		cy.findByRole("button", { name: /next|suivant/i }).click();

		cy.wait("@updateInstitution").its("response.statusCode").should("eq", 200);

		cy.url().should("include", "step=2");
	});

	// TC-OB-03: Step 2 — fill academic year and advance to Step 3
	it("TC-OB-03: Step 2 — fill academic year and advance to Step 3", () => {
		// Stub mutations BEFORE form submit
		cy.intercept("POST", "**/trpc/academicYears.create**", {
			statusCode: 200,
			body: [{ result: { data: { id: "year-stub", name: "2026-2027" } } }],
		}).as("createYear");

		cy.intercept("POST", "**/trpc/terms.create**", {
			statusCode: 200,
			body: [{ result: { data: { id: "term-stub" } } }],
		}).as("createTerm");

		cy.intercept("POST", "**/trpc/academicYears.setActive**", {
			statusCode: 200,
			body: [{ result: { data: { id: "year-stub", status: "active" } } }],
		}).as("setActive");

		cy.visit("/#/onboarding?step=2");

		cy.findByRole("heading", { name: /academic year/i }).should("be.visible");

		// Clear pre-filled year name and type a new one
		cy.findByPlaceholderText("2024-2025").clear().type("2026-2027");

		// useEffect auto-fills term dates when pattern YYYY-YYYY is detected
		cy.findAllByDisplayValue(/2026/).should("have.length.gte", 1);

		cy.findByRole("button", { name: /next|suivant/i }).click();

		cy.wait("@createYear");
		cy.wait("@createTerm");
		cy.wait("@setActive");

		cy.url().should("include", "step=3");
	});

	// TC-OB-04: Step 3 — Tracks pre-filled list visible; clicking Next advances to Step 4
	it("TC-OB-04: Step 3 — Tracks pre-filled list visible; clicking Next advances to Step 4", () => {
		cy.intercept("POST", "**/trpc/tracks.bulkCreate**", {
			statusCode: 200,
			body: [{ result: { data: [] } }],
		}).as("bulkCreateTracks");

		cy.visit("/#/onboarding?step=3");

		cy.findByRole("heading", { name: /tracks/i }).should("be.visible");

		// MINESEC_TRACKS are hard-coded — table shows pre-filled entries even with empty list
		cy.findByRole("table").within(() => {
			cy.findAllByDisplayValue(/scientifique/i).should("have.length.gte", 1);
		});

		cy.findByRole("button", { name: /next|suivant/i }).click();
		cy.wait("@bulkCreateTracks");
		cy.url().should("include", "step=4");
	});

	// TC-OB-05: Step 4 — Subjects pre-filled list visible; clicking Next advances to Step 5
	it("TC-OB-05: Step 4 — Subjects pre-filled list visible; clicking Next advances to Step 5", () => {
		cy.intercept("POST", "**/trpc/subjects.bulkCreate**", {
			statusCode: 200,
			body: [{ result: { data: [] } }],
		}).as("bulkCreateSubjects");

		cy.visit("/#/onboarding?step=4");

		cy.findByRole("heading", { name: /subjects/i }).should("be.visible");

		// DEFAULT_SUBJECTS hard-coded — table shows pre-filled entries
		cy.findByRole("table").within(() => {
			cy.findAllByDisplayValue(/mathematics/i).should("have.length.gte", 1);
		});

		cy.findByRole("button", { name: /next|suivant/i }).click();
		cy.wait("@bulkCreateSubjects");
		cy.url().should("include", "step=5");
	});

	// TC-OB-06: Step 5 — set coefficient value and advance to Step 6
	it("TC-OB-06: Step 5 — set coefficient value and advance to Step 6", () => {
		const trackId = "track-c-stub";
		const subjectId = "subj-math-stub";

		// Override empty-state stubs so the coefficient matrix renders
		// Most-recently registered intercept wins for a given URL
		cy.intercept("**/trpc/tracks.list**", {
			statusCode: 200,
			body: [
				{
					result: {
						data: {
							items: [
								{
									id: trackId,
									name: "Scientifique",
									code: "C",
									cycleLevel: "second_cycle",
									isOfficial: true,
								},
							],
							total: 1,
						},
					},
				},
			],
		});

		cy.intercept("**/trpc/subjects.list**", {
			statusCode: 200,
			body: [
				{
					result: {
						data: {
							items: [
								{
									id: subjectId,
									name: "Mathematics",
									code: "MATH",
									nameFr: "Mathématiques",
								},
							],
							total: 1,
						},
					},
				},
			],
		});

		// Coefficients grid returns empty → all cells start at 0
		cy.intercept("**/trpc/tracks.getCoefficientsGrid**", {
			statusCode: 200,
			body: [{ result: { data: [] } }],
		});

		cy.intercept("POST", "**/trpc/tracks.bulkUpsertCoefficients**", {
			statusCode: 200,
			body: [{ result: { data: [] } }],
		}).as("upsertCoeffs");

		cy.visit("/#/onboarding?step=5");

		cy.findByRole("heading", { name: /coefficient matrix/i }).should(
			"be.visible",
		);

		// The Mathematics row is rendered in the grid; set its coefficient to 6
		cy.findByText(/mathematics/i)
			.closest("tr")
			.within(() => {
				cy.findByRole("spinbutton").clear().type("6");
			});

		cy.findByRole("button", { name: /next|suivant/i }).click();
		cy.wait("@upsertCoeffs");
		cy.url().should("include", "step=6");
	});

	// TC-OB-07: Step 6 — create a class and advance to Step 7
	it("TC-OB-07: Step 6 — create a class and advance to Step 7", () => {
		// Provide an active academic year so the form is not blocked
		cy.intercept("**/trpc/academicYears.list**", {
			statusCode: 200,
			body: [
				{
					result: {
						data: [{ id: "year-stub", name: "2025-2026", status: "active" }],
					},
				},
			],
		});

		// Provide tracks so the track selector is populated
		cy.intercept("**/trpc/tracks.list**", {
			statusCode: 200,
			body: [
				{
					result: {
						data: {
							items: [
								{
									id: "track-d-stub",
									name: "Série D",
									code: "D",
									cycleLevel: "second_cycle",
									isOfficial: true,
								},
							],
							total: 1,
						},
					},
				},
			],
		});

		cy.intercept("POST", "**/trpc/classes.bulkCreate**", {
			statusCode: 200,
			body: [{ result: { data: [] } }],
		}).as("bulkCreateClasses");

		cy.visit("/#/onboarding?step=6");

		cy.findByRole("heading", { name: /classes/i }).should("be.visible");

		// Fill the new-row inputs at the bottom of the table
		cy.findByPlaceholderText(/^name$/i).type("4ème D");
		cy.findByPlaceholderText(/^code$/i).type("4D");

		// Click the "+" icon button that adds the row to the list
		cy.findByPlaceholderText(/^name$/i)
			.closest("tr")
			.find("button")
			.last()
			.click();

		// The added class now appears as an editable row in the table
		cy.findByRole("table").within(() => {
			cy.findAllByDisplayValue("4ème D").should("have.length.gte", 1);
		});

		cy.findByRole("button", { name: /next|suivant/i }).click();
		cy.wait("@bulkCreateClasses");
		cy.url().should("include", "step=7");
	});

	// TC-OB-08: Step 7 — add a staff member and complete onboarding
	it("TC-OB-08: Step 7 — add a staff member and complete onboarding", () => {
		cy.intercept("POST", "**/trpc/staff.bulkCreate**", {
			statusCode: 200,
			body: [{ result: { data: [] } }],
		}).as("bulkCreateStaff");

		cy.visit("/#/onboarding?step=7");

		cy.findByRole("heading", { name: /staff|personnel/i }).should("be.visible");

		// Fill the manual-add staff form
		cy.findByPlaceholderText(/first name/i).type("Marie");
		cy.findByPlaceholderText(/last name/i).type("Biya");
		cy.findByPlaceholderText(/email@school\.cm/i).type(
			"marie.biya@ecole-test.cm",
		);

		// Click the "+" icon button to add the row
		cy.findByPlaceholderText(/email@school\.cm/i)
			.parent()
			.find("button")
			.last()
			.click();

		// The new staff member appears in the preview table
		cy.findByText("Marie").should("be.visible");
		cy.findByText("marie.biya@ecole-test.cm").should("be.visible");

		// Click "Finish setup" to end onboarding — triggers staff.bulkCreate
		cy.findByRole("button", { name: /finish|terminer|compléter/i }).click();
		cy.wait("@bulkCreateStaff");

		// URL leaves /onboarding
		cy.url().should("not.include", "/onboarding");
		cy.url().should("match", /\/#\/$/);
	});
});
