// Generated by Cypress Author — 2026-09-04

describe("Sysadmin Institutions", () => {
	beforeEach(() => {
		cy.loginAs("sysadmin");
		cy.visit("/#/sysadmin/institutions");
		// tRPC queries are batched (httpBatchLink) — cannot use cy.wait("@alias") for GET queries.
		// Wait for the table to render instead.
		cy.findByRole("table", { timeout: 15000 }).should("be.visible");
	});

	// TC-SA-INST-01: Table visible with pagination controls
	it("TC-SA-INST-01: shows institution table and pagination controls", () => {
		cy.findByRole("table").should("be.visible");
		// TablePagination renders "Page X of Y" text — no aria-labelled nav wrapper
		cy.contains(/page \d+ of \d+/i).should("be.visible");
	});

	// TC-SA-INST-02: Search by partial name filters rows; clear restores all
	it("TC-SA-INST-02: search by partial name filters and clears", () => {
		const searchTerm = "Bilingue";

		// Search input uses Input component — select by placeholder text, not role="searchbox"
		cy.findByPlaceholderText(/search by name/i).type(searchTerm);

		// DataTable shows skeleton rows (up to 6) while loading. Wait for content to appear.
		// Institution names may not render as <a> elements — check row text instead.
		cy.contains(/bilingue/i, { timeout: 10000 }).should("be.visible");
		cy.findByRole("table").within(() => {
			cy.findAllByRole("row")
				.not(":first")
				.each(($row) => {
					const text = $row.text().trim();
					// Skip skeleton rows (empty text) — only assert on actual data rows
					if (text) cy.wrap($row).invoke("text").should("include", "Bilingue");
				});
		});

		// Clear the search field
		cy.findByPlaceholderText(/search by name/i).clear();

		// At least the seed institution row is back — wait for the API response
		cy.findByRole("table").within(() => {
			cy.findAllByRole("row", { timeout: 10000 })
				.not(":first")
				.should("have.length.gte", 1);
		});
	});

	// TC-SA-INST-03: Type filter "Lycée" shows only lycee rows
	it("TC-SA-INST-03: type filter shows only matching institution type", () => {
		// Combobox trigger has role="combobox"; type filter is first combobox on page
		cy.findAllByRole("combobox").first().click();
		// CommandItem has role="option" in cmdk — avoid strict anchors due to possible whitespace
		cy.findByRole("option", { name: /lycée/i }, { timeout: 8000 }).click();

		// Wait for filter results — institution names may not be <a> elements
		cy.findByRole("table").within(() => {
			cy.findAllByRole("row", { timeout: 10000 })
				.not(":first")
				.each(($row) => {
					const text = $row.text().trim();
					// Skip skeleton rows — only check actual data rows
					if (text)
						cy.wrap($row)
							.invoke("text")
							.should("match", /lyc[eé]e/i);
				});
		});
	});

	// TC-SA-INST-04: Status filter "Suspended" shows only suspended rows (or empty state)
	it("TC-SA-INST-04: status filter 'Suspended' shows only suspended rows", () => {
		// Status filter is the second combobox on page
		cy.findAllByRole("combobox").eq(1).click();
		cy.findByRole("option", { name: /suspended/i }, { timeout: 8000 }).click();

		// Either suspended rows appear or the empty filter message appears
		cy.get("body", { timeout: 10000 }).then(($body) => {
			const hasRows =
				$body.find("table tbody tr").length > 0 &&
				$body.find("table tbody td[colspan]").length === 0;
			if (hasRows) {
				cy.findByRole("table").within(() => {
					cy.findAllByRole("row")
						.not(":first")
						.each(($row) => {
							const text = $row.text().trim();
							if (text)
								cy.wrap($row)
									.invoke("text")
									.should("match", /suspended|suspendu/i);
						});
				});
			} else {
				// Empty state is acceptable — no suspended institutions in seed; DataTable shows "No results."
				cy.log("No suspended institutions — filter applied correctly");
			}
		});
	});

	// TC-SA-INST-05: Create new institution via dialog, appears in list
	it("TC-SA-INST-05: creates a new institution via dialog", () => {
		cy.interceptTrpc("systemAdmin.createInstitution", "createInst");

		// Open dialog — button text: t("sysadmin.institutions.new_institution", "New Institution")
		cy.findByRole("button", { name: /new institution/i }).click();
		cy.findByRole("dialog").should("be.visible");

		const timestamp = Date.now();
		const instName = `Test School ${timestamp}`;

		// Fill the Name field — FormField has no htmlFor, so findByLabelText fails.
		// Use the first text input inside the dialog.
		cy.findByRole("dialog").within(() => {
			cy.get("input:not([type='hidden']):not([type='checkbox'])")
				.first()
				.type(instName);
		});

		// Submit — button: "Create institution"
		cy.findByRole("button", { name: /create institution/i }).click();

		cy.wait("@createInst").its("response.statusCode").should("eq", 200);

		// Dialog closes
		cy.findByRole("dialog").should("not.exist");

		// New institution appears in the list
		cy.contains(instName).should("be.visible");
	});

	// TC-SA-INST-06 (CRITICAL regression): Cancel button closes dialog without creating.
	it("TC-SA-INST-06 [fr]: Cancel button closes dialog in French locale", () => {
		cy.window().then((win) => {
			win.localStorage.setItem("i18nextLng", "fr");
		});
		cy.reload();
		cy.findByRole("table", { timeout: 15000 }).should("be.visible");

		// French: t("sysadmin.institutions.new_institution") = "Nouvel établissement"
		cy.findByRole("button", {
			name: /nouvel.+tablissement|new institution/i,
		}).click();
		cy.findByRole("dialog").should("be.visible");

		// In French, cancel reads "Annuler"
		cy.findByRole("button", { name: /annuler/i }).click();
		cy.findByRole("dialog").should("not.exist");

		cy.window().then((win) => {
			win.localStorage.setItem("i18nextLng", "en");
		});
	});

	it("TC-SA-INST-06 [en]: Cancel button closes dialog in English locale", () => {
		cy.window().then((win) => {
			win.localStorage.setItem("i18nextLng", "en");
		});
		cy.reload();
		cy.findByRole("table", { timeout: 15000 }).should("be.visible");

		cy.findByRole("button", { name: /new institution/i }).click();
		cy.findByRole("dialog").should("be.visible");

		cy.findByRole("button", { name: /^cancel$/i }).click();
		cy.findByRole("dialog").should("not.exist");
	});
});
