// Generated by Cypress Author — 2026-09-04
// Updated 2026-09-10: Suspend/Reactivate/Delete moved to MoreHorizontal DropdownMenu
//
// Key component facts (sourced from institution-detail.tsx):
// - Tabs are <NavLink> elements inside <div role="tablist"> — links have NO role="tab".
//   Use findByRole("link") to click tabs.
// - Suspend / Reactivate / Delete are DropdownMenuItems inside the MoreHorizontal menu
//   (aria-label="More actions"). Open the menu first, then click the menuitem.
// - Delete uses Confirm.call (react-call) — a dialog appears with a destructive confirm button.
// - Members tab: role changes via "Set as Admin" / "Set as Member" buttons, NOT comboboxes.

const INSTITUTION_NAME = "Lycée Bilingue de Yaoundé";

function navigateToInstitutionDetail() {
	cy.visit("/#/sysadmin/institutions");
	// Wait for the table to load, then click the institution link
	cy.findByRole("table", { timeout: 15000 }).should("be.visible");
	// Use cy.contains — handles accented chars and avoids multiple-match issues
	cy.contains(/bilingue/i, { timeout: 15000 }).click();
	// Overview tab is the default sub-route
	cy.url().should("match", /\/sysadmin\/institutions\/[^/]+\/overview$/);
}

describe("Institution Detail — TC-SA-ID-01 to TC-SA-ID-08", () => {
	beforeEach(() => {
		cy.loginAs("sysadmin");
		navigateToInstitutionDetail();
	});

	// TC-SA-ID-01: Overview tab active by default — stats cards and detail rows visible
	it("TC-SA-ID-01: shows overview tab by default with stats cards and detail rows", () => {
		// Content that appears in the overview tab
		cy.contains(/students|élèves/i, { timeout: 10000 }).should("be.visible");
		cy.contains(/staff|personnel/i).should("be.visible");
		cy.contains(/classes/i).should("be.visible");

		// Detail rows
		cy.contains(/type/i).should("be.visible");
		cy.contains(/status|statut/i).should("be.visible");
		cy.contains(/created|créé/i).should("be.visible");
	});

	// TC-SA-ID-02: Locale-aware date formatting
	it("TC-SA-ID-02: formats date according to locale", () => {
		// Set locale to French and check date format (DD/MM/YYYY or similar)
		cy.window().then((win) => {
			win.localStorage.setItem("i18nextLng", "fr");
		});
		cy.reload();
		// Just verify a date pattern is present somewhere on the page (incl. ISO YYYY-MM-DD)
		cy.get("body")
			.invoke("text")
			.should(
				"match",
				/\d{1,2}[/-]\d{1,2}[/-]\d{4}|\d{1,2}\s+\w+\.?\s+\d{4}|\d{4}-\d{2}-\d{2}/,
			);

		// Set locale to English and check date format
		cy.window().then((win) => {
			win.localStorage.setItem("i18nextLng", "en");
		});
		cy.reload();
		cy.get("body")
			.invoke("text")
			.should(
				"match",
				/\d{1,2}[/-]\d{1,2}[/-]\d{4}|\w+\s+\d{1,2},?\s+\d{4}|\d{4}-\d{2}-\d{2}/,
			);
	});

	// TC-SA-ID-03: Edit institution — dialog pre-populated, save updates name
	it("TC-SA-ID-03: edit dialog pre-populates and saves updated institution name", () => {
		cy.interceptTrpc("systemAdmin.updateInstitution", "updateInstitution");

		// Edit button: t("sysadmin.institution_detail.edit") = "Edit"
		cy.findByRole("button", { name: /^edit$|^modifier$/i }).click();

		// Dialog should open and be pre-populated with institution name
		cy.findByRole("dialog").should("be.visible");
		// The Name label is "Name" in the edit dialog
		cy.findByRole("dialog")
			.find("input:not([type='hidden']):not([type='checkbox']):not(.sr-only)")
			.first()
			.should("have.value", INSTITUTION_NAME);

		// Change the name
		const updatedName = `${INSTITUTION_NAME} (Updated)`;
		cy.findByRole("dialog")
			.find("input:not([type='hidden']):not([type='checkbox']):not(.sr-only)")
			.first()
			.clear()
			.type(updatedName);

		// Save: t("sysadmin.institution_detail.save_changes") = "Save changes"
		cy.findByRole("button", { name: /save changes|enregistrer/i }).click();

		cy.wait("@updateInstitution").its("response.statusCode").should("eq", 200);

		// Dialog should close
		cy.findByRole("dialog").should("not.exist");

		// Updated name should appear in the overview
		cy.contains(updatedName).should("be.visible");

		// Restore original name for subsequent tests
		cy.interceptTrpc("systemAdmin.updateInstitution", "restoreInstitution");
		cy.findByRole("button", { name: /^edit$|^modifier$/i }).click();
		cy.findByRole("dialog")
			.find("input:not([type='hidden']):not([type='checkbox']):not(.sr-only)")
			.first()
			.clear()
			.type(INSTITUTION_NAME);
		cy.findByRole("button", { name: /save changes|enregistrer/i }).click();
		cy.wait("@restoreInstitution");
	});

	// TC-SA-ID-04: Suspend and reactivate institution
	// NOTE: Suspend/Reactivate are DropdownMenuItems inside the MoreHorizontal menu.
	it("TC-SA-ID-04: suspend and reactivate institution changes status badge", () => {
		cy.interceptTrpc("systemAdmin.suspendInstitution", "suspendInst");

		// Open the MoreHorizontal actions dropdown, then click Suspend
		cy.findByRole("button", { name: /more actions/i }).click();
		cy.findByRole("menuitem", { name: /^suspend$|^suspendre$/i }).click();

		cy.wait("@suspendInst").its("response.statusCode").should("eq", 200);

		// Status badge shows "Suspended"
		cy.contains(/suspended|suspendu/i, { timeout: 10000 }).should("be.visible");

		// Open dropdown again — item now says "Reactivate"
		cy.interceptTrpc("systemAdmin.activateInstitution", "activateInst");

		cy.findByRole("button", { name: /more actions/i }).click();
		cy.findByRole("menuitem", { name: /^reactivate$|^réactiver$/i }).click();

		cy.wait("@activateInst").its("response.statusCode").should("eq", 200);

		// Status badge shows "Active"
		cy.contains(/^active$|^actif$/i, { timeout: 10000 }).should("be.visible");
	});

	// TC-SA-ID-05: Members tab — list and role change
	// NOTE: Members tab has "Set as Admin" / "Set as Member" buttons, NOT comboboxes.
	it("TC-SA-ID-05: members tab lists members and allows role change", () => {
		cy.interceptTrpc("systemAdmin.updateMemberRole", "updateMemberRole");

		// Navigate to Members tab — rendered as NavLink (no role="tab"), so use role="link"
		cy.findByRole("link", { name: /members|membres/i }).click();

		cy.url().should("match", /\/sysadmin\/institutions\/[^/]+\/members$/);

		// Members list should be visible with name/email/role columns
		cy.findByRole("table", { timeout: 15000 }).should("be.visible");
		cy.findByRole("table").within(() => {
			cy.findAllByRole("row").not(":first").should("have.length.gte", 1);
		});

		// Change role of the first member: the row has a "Set as Admin" or "Set as Member" button
		cy.findByRole("table").within(() => {
			cy.findAllByRole("row")
				.not(":first")
				.first()
				.within(() => {
					cy.findByRole("button", {
						name: /set as admin|set as member|admin|member/i,
					}).click();
				});
		});

		cy.wait("@updateMemberRole").its("response.statusCode").should("eq", 200);
	});

	// TC-SA-ID-06: Add member — user search, select and add
	it("TC-SA-ID-06: add member via user search and assigns role", () => {
		cy.interceptTrpc("systemAdmin.addMember", "addMember");

		// Navigate to Members tab via link (not role="tab")
		cy.findByRole("link", { name: /members|membres/i }).click();
		cy.url().should("match", /\/sysadmin\/institutions\/[^/]+\/members$/);

		// "Add member" button: t("sysadmin.institution_detail.add_member_button") = "Add member"
		cy.findByRole(
			"button",
			{ name: /add member|ajouter un membre/i },
			{ timeout: 10000 },
		).click();

		// UserSearchField dialog appears
		cy.findByRole("dialog").should("be.visible");

		// Search for sysadmin user "Système Admin" who is NOT a member — teacher already is (409)
		cy.findByPlaceholderText(/search by name or email/i).type("Système");

		// Wait for search results — content-based wait
		cy.findByRole("listbox", { timeout: 8000 }).should("be.visible");
		cy.findAllByRole("option").first().click();

		// Click Add Member button in dialog
		cy.findByRole("dialog").within(() => {
			cy.findByRole("button", { name: /add member|ajouter/i }).click();
		});

		cy.wait("@addMember").its("response.statusCode").should("eq", 200);

		// Dialog should close
		cy.findByRole("dialog").should("not.exist");
	});

	// TC-SA-ID-07: Remove member — confirmation dialog then removes
	it("TC-SA-ID-07: remove member shows confirmation dialog then removes member", () => {
		cy.interceptTrpc("systemAdmin.removeMember", "removeMember");

		cy.findByRole("link", { name: /members|membres/i }).click();
		cy.url().should("match", /\/sysadmin\/institutions\/[^/]+\/members$/);

		cy.findByRole("table", { timeout: 15000 }).should("be.visible");

		// Click Remove on first member row
		cy.findByRole("table").within(() => {
			cy.findAllByRole("row")
				.not(":first")
				.first()
				.within(() => {
					cy.findByRole("button", { name: /remove|supprimer/i }).click();
				});
		});

		// Confirmation dialog should appear
		cy.findByRole("dialog").should("be.visible");

		cy.findByRole("dialog").within(() => {
			cy.findByRole("button", { name: /confirm|remove|supprimer|confirmer/i })
				.last()
				.click();
		});

		cy.wait("@removeMember").its("response.statusCode").should("eq", 200);

		cy.findByRole("dialog").should("not.exist");
	});

	// TC-SA-ID-08: Academic tab — academic years listed or "No academic years"
	it("TC-SA-ID-08: academic tab shows academic years or empty state", () => {
		// Navigate to Academic tab via link (not role="tab")
		cy.findByRole("link", { name: /academic|académique/i }).click();

		cy.url().should("match", /\/sysadmin\/institutions\/[^/]+\/academic$/);

		// Either academic years list or empty state is visible — wait for data to load
		cy.get("body", { timeout: 10000 }).should(
			"satisfy",
			($body: JQuery<HTMLBodyElement>) =>
				$body.text().includes("2025-2026") ||
				$body.find("[data-testid='academic-year-row']").length > 0 ||
				$body.text().match(/no academic years|aucune année académique/i) !==
					null,
		);
	});
});

// TC-SA-ID-09: Delete institution — creates a throwaway institution then deletes it,
// so "Lycée Bilingue de Yaoundé" (the seed institution) is never destroyed and
// subsequent tests and cached sessions remain valid.
describe("Institution Detail — TC-SA-ID-09 Delete", () => {
	beforeEach(() => {
		cy.loginAs("sysadmin");
	});

	it("TC-SA-ID-09: delete institution shows danger dialog then navigates back to list", () => {
		// --- Step 1: Create a throwaway institution via UI ---
		cy.visit("/#/sysadmin/institutions");
		cy.findByRole("table", { timeout: 15000 }).should("be.visible");

		cy.interceptTrpc("systemAdmin.createInstitution", "createThrowaway");
		cy.findByRole("button", {
			name: /new institution|nouvelle institution/i,
		}).click();
		cy.findByRole("dialog").should("be.visible");

		// Use a timestamp-based name so it is unique per run
		const throwawayName = `Delete Test ${Date.now()}`;
		cy.findByRole("dialog").within(() => {
			cy.get("input:not([type='hidden']):not([type='checkbox'])")
				.first()
				.type(throwawayName);
		});
		cy.findByRole("button", { name: /create institution|créer/i }).click();
		cy.wait("@createThrowaway").its("response.statusCode").should("eq", 200);
		cy.findByRole("dialog").should("not.exist");

		// --- Step 2: Navigate to the throwaway institution's detail page ---
		cy.contains(throwawayName, { timeout: 15000 }).click();
		cy.url().should("match", /\/sysadmin\/institutions\/[^/]+\/overview$/);

		// --- Step 3: Delete the throwaway institution ---
		cy.interceptTrpc("systemAdmin.deleteInstitution", "deleteInstitution");

		// Delete is a DropdownMenuItem inside the MoreHorizontal menu
		cy.findByRole("button", { name: /more actions/i }).click();
		cy.findByRole("menuitem", {
			name: /delete institution|supprimer l'institution/i,
		}).click();

		// Confirm.call dialog appears (react-call confirm dialog)
		cy.findByRole("dialog").should("be.visible");

		// Confirm deletion by clicking the destructive confirm button
		cy.findByRole("button", {
			name: /delete institution|supprimer|confirmer/i,
		})
			.last()
			.click();

		cy.wait("@deleteInstitution").its("response.statusCode").should("eq", 200);

		// Navigates back to institutions list
		cy.url().should("include", "/sysadmin/institutions");
		cy.url().should("not.match", /\/sysadmin\/institutions\/.+/);

		// Seed institution is still present
		cy.contains(/bilingue/i, { timeout: 10000 }).should("be.visible");
	});
});
