// Generated by Cypress Author — 2026-09-04

describe("Sysadmin Overview", () => {
	beforeEach(() => {
		cy.loginAs("sysadmin");
		cy.interceptTrpc("systemAdmin.listInstitutions", "listInst");
		cy.visit("/#/sysadmin/");
	});

	// TC-SA-OV-01: KPI cards are visible with numeric values
	it("TC-SA-OV-01: shows KPI cards with numeric values (not skeletons)", () => {
		// Use cy.contains (picks first match) — avoids Testing Library multi-match throws
		cy.contains(/institutions/i).should("be.visible");
		cy.contains(/banned/i).should("be.visible");

		// Assert numeric values rendered (not skeleton placeholder text)
		// StatCard components do not have data-testid — verify page contains at least one digit
		cy.get("body").invoke("text").should("match", /\d+/);
	});

	// TC-SA-OV-02: Growth chart renders or shows empty state
	it("TC-SA-OV-02: growth chart renders area chart or empty state", () => {
		// The chart section should be present
		cy.findByText(/growth|croissance/i).should("exist");

		// Either a chart SVG is rendered (recharts) or an empty-state message
		cy.get("body").then(($body) => {
			// Recharts renders any SVG (class names vary by version); also check empty state text
			const hasSvg = $body.find("svg").length > 0;
			const hasCanvas = $body.find("canvas").length > 0;
			const bodyText = $body.text().toLowerCase();
			const hasEmptyState =
				bodyText.includes("no growth") ||
				bodyText.includes("no data") ||
				bodyText.includes("aucune") ||
				bodyText.includes("empty");

			expect(hasSvg || hasCanvas || hasEmptyState).to.be.true;
		});

		// If SVG present, month labels should exist (x-axis ticks)
		cy.get("svg").then(($svgs) => {
			if ($svgs.length > 0) {
				// Recharts renders month labels in tspan or text elements
				// Just verify the SVG is non-empty (has children)
				cy.get("svg").first().find("*").should("have.length.gt", 0);
			}
		});
	});

	// TC-SA-OV-03: Recent institutions table — rows have expected columns, badge text is correct,
	//              clicking a row navigates to detail page
	it("TC-SA-OV-03: recent institutions table shows correct columns and navigates on row click", () => {
		// httpBatchLink batches queries so the listInst alias may never fire — wait for content instead
		// Use cy.contains (jQuery-based) which handles accented characters better than findByText
		cy.contains(/bilingue/i, { timeout: 15000 }).should("be.visible");

		// Overview uses <div><Link> rows. Seed institution must show "Active" / "Actif" badge.
		cy.get("body").then(($body) => {
			const hasActive =
				$body.text().includes("Active") || $body.text().includes("Actif");
			expect(hasActive).to.be.true;
		});

		// The institution row should show "Active" / "Actif" inside its link
		cy.contains(/bilingue/i)
			.closest("a")
			.within(() => {
				cy.contains(/^(Active|Actif)$/).should("exist");
			});

		// Clicking the institution navigates to its detail page
		cy.contains(/bilingue/i).click();
		cy.url().should("match", /\/sysadmin\/institutions\/[^/]+/);
	});
});
