// Generated by Cypress Author — 2026-09-04

describe("Sysadmin Users", () => {
	beforeEach(() => {
		cy.loginAs("sysadmin");
		cy.visit("/#/sysadmin/users");
		// tRPC queries are batched — cannot use cy.wait("@alias") for GET queries.
		cy.findByRole("table", { timeout: 15000 }).should("be.visible");
	});

	// TC-SA-USR-01: Paginated user list; search filters results
	it("TC-SA-USR-01: shows paginated user list and search filters by name/email", () => {
		// List is visible
		cy.findByRole("table").should("be.visible");

		// TablePagination renders "Page X of Y" — no aria-labelled nav wrapper
		cy.contains(/page \d+ of \d+/i).should("be.visible");

		// Search by name — Input has placeholder "Search by name or email…"
		cy.findByPlaceholderText(/search by name or email/i).type("nkemdirim");

		// DataTable shows skeleton rows (up to 6) while loading. Wait for actual data links.
		cy.findByRole("table").within(() => {
			cy.findAllByRole("link", { timeout: 10000 }).should("have.length.gte", 1);
			cy.findAllByRole("row")
				.not(":first")
				.each(($row) => {
					const text = $row.text().trim();
					// Skip skeleton rows (empty text) — only assert on actual data rows
					if (text)
						cy.wrap($row)
							.invoke("text")
							.should("match", /nkemdirim/i);
				});
		});

		// Clear search — all rows return
		cy.findByPlaceholderText(/search by name or email/i).clear();

		// Wait for the API to respond after clearing the search
		cy.findByRole("table").within(() => {
			cy.findAllByRole("row", { timeout: 10000 })
				.not(":first")
				.should("have.length.gte", 1);
		});
	});

	// TC-SA-USR-02 (CRITICAL): Cancel button closes any user-page dialog in fr and en
	it("TC-SA-USR-02 [fr]: Cancel closes dialog in French locale", () => {
		cy.window().then((win) => {
			win.localStorage.setItem("i18nextLng", "fr");
		});
		cy.reload();
		cy.findByRole("table", { timeout: 15000 }).should("be.visible");

		// "Create account" button: t("sysadmin.users.create_user", "Create account") → "Créer un compte" in FR
		// But the regex /invite|ban|create|new|nouvel|inviter/i should match
		cy.findByRole("button", {
			name: /invite|ban|cr[eé]er|create|new|nouvel|inviter/i,
		})
			.first()
			.click();

		cy.findByRole("dialog").should("be.visible");

		cy.findByRole("button", { name: /annuler/i }).click();
		cy.findByRole("dialog").should("not.exist");

		cy.window().then((win) => {
			win.localStorage.setItem("i18nextLng", "en");
		});
	});

	it("TC-SA-USR-02 [en]: Cancel closes dialog in English locale", () => {
		cy.window().then((win) => {
			win.localStorage.setItem("i18nextLng", "en");
		});
		cy.reload();
		cy.findByRole("table", { timeout: 15000 }).should("be.visible");

		// Button text: "Create account"
		cy.findByRole("button", { name: /create account|invite|ban|create|new/i })
			.first()
			.click();

		cy.findByRole("dialog").should("be.visible");

		cy.findByRole("button", { name: /^cancel$/i }).click();
		cy.findByRole("dialog").should("not.exist");
	});

	// TC-SA-USR-03: Clicking user row navigates to profile detail page
	it("TC-SA-USR-03: clicking user row navigates to /sysadmin/users/:id", () => {
		// Wait for data to load, then click the seed teacher name link (Name column = <a> Link)
		cy.findByRole("table").within(() => {
			cy.contains("a", /nkemdirim/i, { timeout: 10000 }).click();
		});

		// URL goes to /sysadmin/users/:id (may redirect to /profile)
		cy.url({ timeout: 10000 }).should("include", "/sysadmin/users/");

		// Profile page shows name
		cy.contains(/nkemdirim/i, { timeout: 10000 }).should("be.visible");
		// email contains @
		cy.get("body").invoke("text").should("match", /@/);
		// Date — "04 Sept 2026" format (DD Mon YYYY) or ISO
		cy.get("body")
			.invoke("text")
			.should(
				"match",
				/\d{2}\s+\w+\s+\d{4}|\d{4}-\d{2}-\d{2}|\d{2}[/\-.]\d{2}[/\-.]\d{4}/,
			);
	});

	// TC-SA-USR-04: Ban user → status shows Banned; Unban → status reverts
	it("TC-SA-USR-04: ban and unban user changes status", () => {
		// Navigate to the teacher user's detail page via name Link (scoped within table)
		cy.findByRole("table").within(() => {
			cy.contains("a", /nkemdirim/i, { timeout: 10000 }).click();
		});
		cy.url({ timeout: 10000 }).should("include", "/sysadmin/users/");

		// Click ban action — button text: t("sysadmin.users.detail.ban_action", "Ban")
		cy.findByRole("button", { name: /^ban$/i }, { timeout: 10000 }).click();

		// Ban dialog opens (BanDialog component with reason + duration fields)
		// Confirm by clicking the destructive "Ban user" button in the dialog
		cy.findByRole("dialog").should("be.visible");
		cy.findByRole("button", { name: /^ban user$|^bannir$/i })
			.last()
			.click();

		// Wait for ban to complete — status badge shows "Banned"
		cy.contains(/^banned$/i, { timeout: 10000 }).should("be.visible");

		// Unban is in the MoreHorizontal DropdownMenu
		cy.findByRole("button", { name: /more actions/i }).click();
		cy.findByRole("menuitem", { name: /^unban$|^débannir$/i }).click();

		// Status reverted — "Banned" badge gone
		cy.contains(/^banned$/i, { timeout: 10000 }).should("not.exist");
	});

	// TC-SA-USR-05: User memberships tab shows orgs with name, role, joined date
	it("TC-SA-USR-05: memberships tab lists organisations with name, role, and joined date", () => {
		// Search for admin user to ensure they appear on page 1 (pagination may hide them)
		cy.findByPlaceholderText(/search by name or email/i).type("Admin");

		// Navigate to admin user via their NAME (Link) — email cell is not a link
		// Seed admin name is "Admin Lycée" (admin@lycee-bilingue.local)
		// Use a longer timeout to allow search debounce + API response.
		cy.findByRole("table").within(() => {
			cy.contains("a", /admin lyc/i, { timeout: 15000 }).click();
		});
		cy.url({ timeout: 10000 }).should("include", "/sysadmin/users/");

		// Click the Memberships tab — rendered as NavLink (not role="tab")
		cy.findByRole(
			"link",
			{ name: /memberships?/i },
			{ timeout: 10000 },
		).click();

		cy.url({ timeout: 10000 }).should("include", "/memberships");

		// At least one membership row (admin belongs to an institution)
		cy.findByRole("table", { timeout: 10000 }).within(() => {
			cy.findAllByRole("row").not(":first").should("have.length.gte", 1);
		});

		// Role label — orgRole is displayed (Admin or member)
		cy.contains(/admin|member/i).should("exist");

		// Joined date — "04 Sept 2026" format (DD Mon YYYY) or ISO
		cy.get("body")
			.invoke("text")
			.should(
				"match",
				/\d{2}\s+\w+\s+\d{4}|\d{4}-\d{2}-\d{2}|\d{2}[/\-.]\d{2}[/\-.]\d{4}/,
			);
	});
});
